{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig-posthog/0.27.0/core-remoteconfig-posthog-0.27.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-posthog",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-iosSimulatorArm64Main-0.27.0.klib",
          "url": "core-remoteconfig-posthog-iossimulatorarm64-0.27.0.klib",
          "size": 16504,
          "sha512": "b029b4c567f8c8383707f7f489d1e20ffba5151aaec5db9fba732da62a86c166ebd1b56fbbacbae29a027fe11b7b7cb7aa172a4ce30ea9ccf43a575225c1d3d7",
          "sha256": "92505852d499f89d7ca7d5468f29ce0960f93ab7bd8554d2c74467ad452ca291",
          "sha1": "d17ec4d331092f5b1fa0ac9dbefe81e65d5949cb",
          "md5": "f6ac48e61fd65d9548166fa5443f3609"
        },
        {
          "name": "core-remoteconfig-posthog-iosSimulatorArm64Cinterop-PostHogMain-0.27.0.klib",
          "url": "core-remoteconfig-posthog-iossimulatorarm64-0.27.0-cinterop-PostHog.klib",
          "size": 21571,
          "sha512": "910188dbb1cf261f5fdc6ee4f39648df67ec795036cdce4444302ea104c899a100f361c8a56e493487ab21408d77fff5f129d2500127d18eace9c5d5f193e8dd",
          "sha256": "8565909ed49967023175b3d9d2af62de580360f7ed7090835c7d8e5ce95267e3",
          "sha1": "4563a7ca109bb0d6fa012f33720be78ee544686e",
          "md5": "88d17e46c80287ab85a9acbf07174275"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-posthog-iossimulatorarm64-0.27.0-sources.jar",
          "url": "core-remoteconfig-posthog-iossimulatorarm64-0.27.0-sources.jar",
          "size": 5224,
          "sha512": "f011cc9ab80c3f5c23a15f78d071a90d573211ce6769fb2bcfb256a3f9f17d043ed5bf78bf3aa5eb1a2bcb62a0878cc238ff50b9aa0f3a39e1b3747d137746c0",
          "sha256": "509e63a4bceee9a217759e53e2f26326772dcdae702e701641f3c99dec7367f2",
          "sha1": "0869348d3acad764d6bae1b814141aa77a39921d",
          "md5": "00128daf39b5d3af1a3c976e6fc79a15"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-iossimulatorarm64-0.27.0-metadata.jar",
          "url": "core-remoteconfig-posthog-iossimulatorarm64-0.27.0-metadata.jar",
          "size": 56500,
          "sha512": "9874e258345117504cbc1b09867abcf248bb6a0c6170232f1bfd98ea95b9533665f7d19a756debface3ccab379d510b0eab200136ec79fd416eb7f54d7b922a6",
          "sha256": "a72ca07fb47380e19a695d2c7b51274df04ce203d36e318b704e5a8703636700",
          "sha1": "f8c808f2a2455faa3eddc362fc8103e33908c674",
          "md5": "f87b6356ded43813b94da4aa88d741d4"
        }
      ]
    }
  ]
}
