{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-logger",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-metadata-0.24.1.jar",
          "url": "core-logger-0.24.1.jar",
          "size": 24306,
          "sha512": "b399d421db37ec8ba91b9e743b8ad949737b7734bf97af6b3769c35e63cd9988c64532281602c0607715f994a3a12cbbb9a9d29be5735fc3b67b49c59b58c5d2",
          "sha256": "e0fdd3d49358cb01f01c3d4b7bb60dcb9a63a46994e59ccefb8ecb015fe98db3",
          "sha1": "3557427c139e706a6b862c40c9e8045e9e16b3a0",
          "md5": "8b95264508141695ca3f3499f5b29e3e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-logger-kotlin-0.24.1-sources.jar",
          "url": "core-logger-0.24.1-sources.jar",
          "size": 23929,
          "sha512": "cf958895c1ce6a6a6090e93ba12c99710f053fe884808334af3b62f031abb34a81aba0efc56e1b2f2fcc8cd7e1724b87b9eb016dafd6211d065f5896e038f656",
          "sha256": "930f720b54f98939c6e69d89db644ab7ce9e508152369add5f5217ce604c4bab",
          "sha1": "07c947f0acc1f4eb7c6985f84522bd0160e84b3e",
          "md5": "d165fe24e4fa62a835a3a34a86e2a56d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-android/0.24.1/core-logger-android-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-android",
        "version": "0.24.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-android/0.24.1/core-logger-android-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-android",
        "version": "0.24.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-android/0.24.1/core-logger-android-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-android",
        "version": "0.24.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-iosarm64/0.24.1/core-logger-iosarm64-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-iosarm64",
        "version": "0.24.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-iosarm64/0.24.1/core-logger-iosarm64-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-iosarm64",
        "version": "0.24.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-iosarm64/0.24.1/core-logger-iosarm64-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-iosarm64",
        "version": "0.24.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-iossimulatorarm64/0.24.1/core-logger-iossimulatorarm64-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-iossimulatorarm64",
        "version": "0.24.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-iossimulatorarm64/0.24.1/core-logger-iossimulatorarm64-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-iossimulatorarm64",
        "version": "0.24.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-iossimulatorarm64/0.24.1/core-logger-iossimulatorarm64-0.24.1.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-iossimulatorarm64",
        "version": "0.24.1"
      }
    }
  ]
}
