{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-annotation",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-metadata-0.23.0.jar",
          "url": "core-annotation-0.23.0.jar",
          "size": 4840,
          "sha512": "9b268cbae028ebc7221066a62db74e3ac0eb7e66903cc7c285c8743f68379d1ec610286947012245214d5db6bc63a63a8b795b8d6cb20c23c5fb36d153c7bc30",
          "sha256": "804181ed72497d615e04b489352402dcfd79e4cd3d9ebe600080eba89f3a7b94",
          "sha1": "44eb559d0ba9e0cb49fbd60e0dfe25d511129bf3",
          "md5": "9c638d4c850cea550560d4c91454decb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "annotation-kotlin-0.23.0-sources.jar",
          "url": "core-annotation-0.23.0-sources.jar",
          "size": 3421,
          "sha512": "d4a0fe87a08492aa7782b988891720240ff4d95d497e7b952b72cc3400e043a08ed60ffd32e3b841a6a83d9658bec7676a58cc97355ab5df2f0c913b1f61ecae",
          "sha256": "a5a6f44fed26ca24da7e18e0e932831b979dd21bc60de115ee520340cb64ba63",
          "sha1": "a5cee5928dd72956a7b6c60f21145e3c05e84cec",
          "md5": "14ab7d440ff6f9aa670c6aab091ed4ff"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-annotation-android/0.23.0/core-annotation-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-annotation-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-annotation-android/0.23.0/core-annotation-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-annotation-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-annotation-android/0.23.0/core-annotation-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-annotation-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/0.23.0/annotation-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/0.23.0/annotation-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/0.23.0/annotation-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/0.23.0/annotation-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/0.23.0/annotation-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/0.23.0/annotation-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/0.23.0/annotation-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/0.23.0/annotation-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/0.23.0/annotation-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "annotation-iosx64",
        "version": "0.23.0"
      }
    }
  ]
}
