{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.23.0/core-remoteconfig-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "remoteconfig-iosArm64Main-0.23.0.klib",
          "url": "remoteconfig-iosarm64-0.23.0.klib",
          "size": 16938,
          "sha512": "274ae5226040c78d801d19b147212ec2742eb8492e8676177e64902b9c2a5905fcaf6c246e4316cd0de5ac1e29212acf739b86080d0876713ac61f7d8c368506",
          "sha256": "2954e76d66675eac342175fee3ec65fd1ce15741b40e4b74bda1e1a5e986084e",
          "sha1": "646bf34d25695e7c9689c69b101b84d6ea3e8cc1",
          "md5": "0c0430c0578e21ffa60e5fc4581a27b7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "remoteconfig-iosarm64-0.23.0-sources.jar",
          "url": "remoteconfig-iosarm64-0.23.0-sources.jar",
          "size": 5911,
          "sha512": "80324a440ee63060b4ec2b7238516b6e191d40d41e5719093e2731b9b124ca1c0500be21264301227c132f7c840e291b6bcfcbe990e20d0230fb37fd91cec712",
          "sha256": "31c6b3dd523d0dfa8013d82c7080448dcb4621ebcbf25394f00ab957cf18863e",
          "sha1": "58b7aaf98ebce30a132bd2e82f05902727e98b86",
          "md5": "73fa0791cfbd433abc542059e2a5593b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "remoteconfig-iosarm64-0.23.0-metadata.jar",
          "url": "remoteconfig-iosarm64-0.23.0-metadata.jar",
          "size": 261,
          "sha512": "079aedf0b41563bac1d6335d6c6d12ed23e606b1f90bb3c9e800b460d1e2e3eb4386a93598acf0b52d4451f28d032f3bf5b9701fdb8690c8e9710bf81222a4e8",
          "sha256": "a0821a8983573f3c773c55e2122f5c4236e80a055be8af4200f3a8d9d794183f",
          "sha1": "570b804d7128bb65535929723516494bc1728db8",
          "md5": "0668b35e7188a38fae1ddd798e0e1f96"
        }
      ]
    }
  ]
}
