{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ui",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.18.0.aar",
          "url": "core-ui-0.18.0.aar",
          "size": 152729,
          "sha512": "b3401f1a2026fae733b31664255971e20492f1ee72fe4096ed0e4d1042d3c6169cfe056e9992bf137c1f06084fa6d0f1a0030814284edb814b734c59a89e41f9",
          "sha256": "ad407e41091b50af0a6c17a738f6e73586ff084a211262270c91787682f3d87b",
          "sha1": "02c008deafb7bee28332d5ea1e909ebf460ed470",
          "md5": "74de7116203857a7aa9c3cc4b9bdf68d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.18.0.aar",
          "url": "core-ui-0.18.0.aar",
          "size": 152729,
          "sha512": "b3401f1a2026fae733b31664255971e20492f1ee72fe4096ed0e4d1042d3c6169cfe056e9992bf137c1f06084fa6d0f1a0030814284edb814b734c59a89e41f9",
          "sha256": "ad407e41091b50af0a6c17a738f6e73586ff084a211262270c91787682f3d87b",
          "sha1": "02c008deafb7bee28332d5ea1e909ebf460ed470",
          "md5": "74de7116203857a7aa9c3cc4b9bdf68d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ui-0.18.0-sources.jar",
          "url": "core-ui-0.18.0-sources.jar",
          "size": 30989,
          "sha512": "3a4d6d309bcd12042ad0b882fdbd769048b7f8698c9c56dcfb888b0154d829a1e71d1fb9f17ac9c7b4ccddeed811da8d4c67d2f8d2964a867001556231ce633c",
          "sha256": "a9fc0e3861b0514992dfc3ad08d8e7136c3944d77aad248c1a4c5db32a843267",
          "sha1": "3aecadb5a530b1c2d2711f993d66238ab94749cd",
          "md5": "e53f9dbacf5dda90feffadb939629a91"
        }
      ]
    }
  ]
}
