{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-di-koin",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.18.0.aar",
          "url": "core-di-koin-0.18.0.aar",
          "size": 25194,
          "sha512": "1b93d850d55e23ac1f82063d56c13bb942a217bab2db1ff21840c4bf1c8f20605a91a094abd9d07de553a04cc525681792b69a6f55d7305e3454fa132c21cfd3",
          "sha256": "2758866ab9f770aa3a6c5630c1ac175eb2c0ea7ec1f2c6aff925d636311e8b20",
          "sha1": "b5fdf6f69b010e60155b534ade7c841acff0a5ea",
          "md5": "cb1010e78a7ac1eff7a0f5e52d7ad28c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-work",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.18.0.aar",
          "url": "core-di-koin-0.18.0.aar",
          "size": 25194,
          "sha512": "1b93d850d55e23ac1f82063d56c13bb942a217bab2db1ff21840c4bf1c8f20605a91a094abd9d07de553a04cc525681792b69a6f55d7305e3454fa132c21cfd3",
          "sha256": "2758866ab9f770aa3a6c5630c1ac175eb2c0ea7ec1f2c6aff925d636311e8b20",
          "sha1": "b5fdf6f69b010e60155b534ade7c841acff0a5ea",
          "md5": "cb1010e78a7ac1eff7a0f5e52d7ad28c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-di-koin-0.18.0-sources.jar",
          "url": "core-di-koin-0.18.0-sources.jar",
          "size": 5780,
          "sha512": "9a5c011ba35480deef5e8fc59e7309934f4ed004260a157a7a85b956f175921e82434d37278dd51c2b8e0a26471b8e478197896d747408bf13415636e92d6745",
          "sha256": "b0ae27629d934495ca09ac9942e6126d5f4c62a7201b2b0ebc9824dcac51f4d3",
          "sha1": "816ecffb5c85e8db2a912db007cbd50f8562ab0a",
          "md5": "a3f2638e6409e54a1cd87da18a23835b"
        }
      ]
    }
  ]
}
