{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.12.0.jar",
          "url": "core-ksp-processor-0.12.0.jar",
          "size": 33243,
          "sha512": "163f9060c429b4f406aa7e0b1b358f8f3e65d4471cc666eb03877e3ae49bc8d361bd915eb34d3e862d02a2e52bdba5a253d070ad3a06e372503fe3d436e3ce29",
          "sha256": "6cc8059d0ea758191771d2145aae2839ab82226a8a2d77736b5bfc3dfcc18034",
          "sha1": "2e0e40da5bdcd84a4a7a77f18ea45e4c0d6f17ba",
          "md5": "f7790e6922b8ce7004518630cde2ddb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.12.0.jar",
          "url": "core-ksp-processor-0.12.0.jar",
          "size": 33243,
          "sha512": "163f9060c429b4f406aa7e0b1b358f8f3e65d4471cc666eb03877e3ae49bc8d361bd915eb34d3e862d02a2e52bdba5a253d070ad3a06e372503fe3d436e3ce29",
          "sha256": "6cc8059d0ea758191771d2145aae2839ab82226a8a2d77736b5bfc3dfcc18034",
          "sha1": "2e0e40da5bdcd84a4a7a77f18ea45e4c0d6f17ba",
          "md5": "f7790e6922b8ce7004518630cde2ddb3"
        }
      ]
    }
  ]
}
