{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-annotation/0.25.0/core-annotation-0.25.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-annotation",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-annotation-iosArm64Main-0.25.0.klib",
          "url": "core-annotation-iosarm64-0.25.0.klib",
          "size": 8990,
          "sha512": "c9004e50cc3763f26812915e4ecc43b68e77632a0a3abe81bf2c4388e699cfdfabb59703e1df8c5d29aace90cad8d6ed4ef3ec2056312f3b9ff3e9d9ba4130c2",
          "sha256": "aa0af91c4c36f63f7cf2b388c18de8f0cb1154d93afd01d9cd1e9379e2d7edc5",
          "sha1": "a85a9a3f29b9b4ea78f4908ce27456d2b84bf98c",
          "md5": "730d5d596daf4316b834571b9dc8ea51"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-annotation-iosarm64-0.25.0-sources.jar",
          "url": "core-annotation-iosarm64-0.25.0-sources.jar",
          "size": 3421,
          "sha512": "d4a0fe87a08492aa7782b988891720240ff4d95d497e7b952b72cc3400e043a08ed60ffd32e3b841a6a83d9658bec7676a58cc97355ab5df2f0c913b1f61ecae",
          "sha256": "a5a6f44fed26ca24da7e18e0e932831b979dd21bc60de115ee520340cb64ba63",
          "sha1": "a5cee5928dd72956a7b6c60f21145e3c05e84cec",
          "md5": "14ab7d440ff6f9aa670c6aab091ed4ff"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-annotation-iosarm64-0.25.0-metadata.jar",
          "url": "core-annotation-iosarm64-0.25.0-metadata.jar",
          "size": 261,
          "sha512": "c17bf02c9a76141d8515a4e2f46ed794d504d7a7df5085c937c69c738fc73a5c2fed1738419617568bfeaca41897b436d9df87fcc3eeb41d3877eed6cb6c94b6",
          "sha256": "4b3b091258fa4405331a76912a69d5c716567b576be4f2db571944c8b3ef7ad2",
          "sha1": "a01955bb5b3f91ccb86610f788ed4cfd9dd1c1bf",
          "md5": "1106eed6681bbcaf1305a91a4020e182"
        }
      ]
    }
  ]
}
