{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-di-hilt",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-hilt-0.11.0.aar",
          "url": "core-di-hilt-0.11.0.aar",
          "size": 36075,
          "sha512": "933f5ed8352b5e348899105f0807b572675b05241574b0333544fb438a0fc761894197e6b6c9817ba8e6882e2dfefeb29a10a8e9015f678b127995eb5a09cfe9",
          "sha256": "ef23f00c19482db97d6770e288c062f416013ae3ab1f401d113dcf2d5d274342",
          "sha1": "b88273c7f6ffaec98d6980ef37c1c8feb688bdb7",
          "md5": "69ea02d8c306bcaa3676d737eef5f734"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-hilt-0.11.0.aar",
          "url": "core-di-hilt-0.11.0.aar",
          "size": 36075,
          "sha512": "933f5ed8352b5e348899105f0807b572675b05241574b0333544fb438a0fc761894197e6b6c9817ba8e6882e2dfefeb29a10a8e9015f678b127995eb5a09cfe9",
          "sha256": "ef23f00c19482db97d6770e288c062f416013ae3ab1f401d113dcf2d5d274342",
          "sha1": "b88273c7f6ffaec98d6980ef37c1c8feb688bdb7",
          "md5": "69ea02d8c306bcaa3676d737eef5f734"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-di-hilt-0.11.0-sources.jar",
          "url": "core-di-hilt-0.11.0-sources.jar",
          "size": 24493,
          "sha512": "a329a91e31d458f47db159ae98dfa728355df3a0a7e001f1b54c0e4fd2c23ca480f576967962f6654cf23b3c597233e72012e015a661ddd1f7e4e3b401a1f6e7",
          "sha256": "fca41c90fdb3a0d15329010e94ff20a6169a5db8085b36dcb1f0a7ceb5d1b171",
          "sha1": "85c1f147382a95c63253cd0ce5a072343ab898a6",
          "md5": "bf42f522cdb01b87146a3c07d9685f7b"
        }
      ]
    }
  ]
}
