{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.26.0.jar",
          "url": "core-ksp-processor-0.26.0.jar",
          "size": 33555,
          "sha512": "ee844587b5232e9c6e463b6367d2177f7e990f722e832cf827b8235dabf619277631ab9849137e1f95f4534daaea18f2a0c6a5ebc1600a7efd5beb3b08573c1c",
          "sha256": "079da253a1eb61dfdb1b578d77f92c6eebd9edbeafb83e1d817eab8a9ea25b33",
          "sha1": "5554707a4b16d7cd2cb4c92e450f1837fa48a174",
          "md5": "8350c2f668807b1a4a1e8670b09e86cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.26.0.jar",
          "url": "core-ksp-processor-0.26.0.jar",
          "size": 33555,
          "sha512": "ee844587b5232e9c6e463b6367d2177f7e990f722e832cf827b8235dabf619277631ab9849137e1f95f4534daaea18f2a0c6a5ebc1600a7efd5beb3b08573c1c",
          "sha256": "079da253a1eb61dfdb1b578d77f92c6eebd9edbeafb83e1d817eab8a9ea25b33",
          "sha1": "5554707a4b16d7cd2cb4c92e450f1837fa48a174",
          "md5": "8350c2f668807b1a4a1e8670b09e86cb"
        }
      ]
    }
  ]
}
