{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-0.23.0.jar",
          "url": "core-foundation-0.23.0.jar",
          "size": 8458,
          "sha512": "3259d2a698349c4d7ecdde80f84b01f2d0651ee1c8e4730086d8ea6bee626acb373293f484d32599bbaa5d780552ed0531b16ea9f83c9950f4c350d209fef491",
          "sha256": "1c6be71c2c76594baa9dd4ea93c728b7a0fd63d167f1e6dbccbb7437745a8bd3",
          "sha1": "fb3fbc0da9897405cc4f15714df618e2ca0eec68",
          "md5": "259853f7fe033a379989ea00e6fc3d8a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "foundation-kotlin-0.23.0-sources.jar",
          "url": "core-foundation-0.23.0-sources.jar",
          "size": 8352,
          "sha512": "7e377f30a7a8d9fdc427fbe7173cbe6298656dba884c10c551b6dafedc24ea08a83b67343a8cdeedd7a16f7b9d35a14fb521070d31739bb56448d25edd2e9d15",
          "sha256": "0441ab2ef4ad0b9a3167367264af20d4e311bd587c9743f454cee3d3868b0fe3",
          "sha1": "3a42842aade89eaf20028586c9ba837036d639f4",
          "md5": "db0fa802910c686e0592b8004db8f1e2"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.23.0/core-foundation-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.23.0/core-foundation-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.23.0/core-foundation-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.23.0/foundation-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.23.0/foundation-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.23.0/foundation-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.23.0/foundation-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.23.0/foundation-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.23.0/foundation-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.23.0/foundation-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.23.0/foundation-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.23.0/foundation-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.23.0"
      }
    }
  ]
}
