{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-work/0.7.0/core-work-0.7.0.module",
    "group": "com.dexkot.mobile",
    "module": "core-work",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-release.aar",
          "url": "core-work-android-0.7.0.aar",
          "size": 93445,
          "sha512": "05cee9e2b39373bebbcf1b2862dd70cee390cb19d69c9811ba62ddd5c1ad31dd926c5e000ad7c90552ebf35e66be5b7b47e1065a7e3711cc6490ca22dfff5eb9",
          "sha256": "84b40018e28cfbe84f1d4fc892ceb8a0ddcf6af4ace006a72dec0f274d5ecc0c",
          "sha1": "1c48fadf50b9d099d31f9b5d130d0ef4534f0fbe",
          "md5": "105438543e722829a231046ed5267958"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "work-release.aar",
          "url": "core-work-android-0.7.0.aar",
          "size": 93445,
          "sha512": "05cee9e2b39373bebbcf1b2862dd70cee390cb19d69c9811ba62ddd5c1ad31dd926c5e000ad7c90552ebf35e66be5b7b47e1065a7e3711cc6490ca22dfff5eb9",
          "sha256": "84b40018e28cfbe84f1d4fc892ceb8a0ddcf6af4ace006a72dec0f274d5ecc0c",
          "sha1": "1c48fadf50b9d099d31f9b5d130d0ef4534f0fbe",
          "md5": "105438543e722829a231046ed5267958"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "work-android-0.7.0-sources.jar",
          "url": "core-work-android-0.7.0-sources.jar",
          "size": 42851,
          "sha512": "eab33ac5e31af9fc772ad16a8ab5b06ba270faee7ff613a952c4f0ff47e3d227d56b88ca682497f3cb26d1de7a68e169c08f23a1cb0e4da57fff403f9916915c",
          "sha256": "8eab0052a111d3190aa01a1d6ebdfef3176096926e24c0f6d1a9eef0eb1680dd",
          "sha1": "c97dd9f7ddce017296ebac2781072c1434258356",
          "md5": "d3e385e9ffdf5016c469980bd0443e53"
        }
      ]
    }
  ]
}
