{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-work/0.26.0/core-work-0.26.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-work",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-iosSimulatorArm64Main-0.26.0.klib",
          "url": "core-work-iossimulatorarm64-0.26.0.klib",
          "size": 59313,
          "sha512": "49e7e74c2c85b0060d8c3d093b01efe43b7c82231f1ab9b900886dfab02c1765bc38f3319e858943c40f4f0783e8ebff7398fca2d1e3a4ea4c63208390a1f01d",
          "sha256": "628176fe4093cff57f7df1c53adbbdcf12858b2cc66519253fe51d6a44f1a294",
          "sha1": "17a4363813b940752ed785b8d8ff967ed68b4186",
          "md5": "5c1fcfcb1fb0015d5be49985db1c6303"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-work-iossimulatorarm64-0.26.0-sources.jar",
          "url": "core-work-iossimulatorarm64-0.26.0-sources.jar",
          "size": 25976,
          "sha512": "22c5fb54113421684ed0150038bcd931caeb4294bac796ca118c88ade9b53e84b33a5ae89666c9018177fb843eb8052875ba74a7fbfe1333a0ad0e065dd5f3b4",
          "sha256": "ae5842426c1bc8607192f16aaec09e5220a818af5a74f871a851fbeaac9bd53c",
          "sha1": "6b5608739049538d939614a8333b168bd12fb839",
          "md5": "4f819f6ccaebab92c04cab94960f28e0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-iossimulatorarm64-0.26.0-metadata.jar",
          "url": "core-work-iossimulatorarm64-0.26.0-metadata.jar",
          "size": 261,
          "sha512": "f2069a11c1fa92e48894e84b7a3d66e0b605dba4eeab44734eb6cbc38ceacf46344cbcbd831feb65d095083ab80765d470579775aa76711330949bbc5b4218e0",
          "sha256": "4438788274992c6e9b2b3f0e0bd71e2c96ab8392d85fc71c1bfad9a4b8cc45b5",
          "sha1": "3f31a26b24bcc1faa5f29ef47d758e185700a23c",
          "md5": "7f9c39841df4c86515e6a42ebc549b24"
        }
      ]
    }
  ]
}
