{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-annotation/0.23.0/core-annotation-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-annotation",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-release.aar",
          "url": "core-annotation-android-0.23.0.aar",
          "size": 4045,
          "sha512": "699135a9c07bbc397eba995573107635b18a956040335f2394d937f476f0ae727af43dd1bb37525f65310448387c5cdc12e86ed879c7da80f9be505f6b6a8cba",
          "sha256": "8e3af71c2bf00ad453daee3e3b21b686e01d26833af2aeabdd158c484ecb5bd5",
          "sha1": "f1929d9e707e8cd9b44e077940f444582e91b8e0",
          "md5": "7449723b7a54761c81276f02d9ead331"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "annotation-release.aar",
          "url": "core-annotation-android-0.23.0.aar",
          "size": 4045,
          "sha512": "699135a9c07bbc397eba995573107635b18a956040335f2394d937f476f0ae727af43dd1bb37525f65310448387c5cdc12e86ed879c7da80f9be505f6b6a8cba",
          "sha256": "8e3af71c2bf00ad453daee3e3b21b686e01d26833af2aeabdd158c484ecb5bd5",
          "sha1": "f1929d9e707e8cd9b44e077940f444582e91b8e0",
          "md5": "7449723b7a54761c81276f02d9ead331"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "annotation-android-0.23.0-sources.jar",
          "url": "core-annotation-android-0.23.0-sources.jar",
          "size": 3421,
          "sha512": "d4a0fe87a08492aa7782b988891720240ff4d95d497e7b952b72cc3400e043a08ed60ffd32e3b841a6a83d9658bec7676a58cc97355ab5df2f0c913b1f61ecae",
          "sha256": "a5a6f44fed26ca24da7e18e0e932831b979dd21bc60de115ee520340cb64ba63",
          "sha1": "a5cee5928dd72956a7b6c60f21145e3c05e84cec",
          "md5": "14ab7d440ff6f9aa670c6aab091ed4ff"
        }
      ]
    }
  ]
}
