{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-database-sqldelight/0.23.0/core-database-sqldelight-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-database-sqldelight",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-database",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "database-sqldelight-iosX64Main-0.23.0.klib",
          "url": "database-sqldelight-iosx64-0.23.0.klib",
          "size": 20241,
          "sha512": "4c28c5b988a7bd982c8218a407afb34e8a18df6983c0d882835bf573ace743fc4e3872c2a118b3f26f3d0ecce33492fd1de5c7f2ba6fa5e42d17e2e02b9e3bb8",
          "sha256": "72950d16e5f08a71af4084a9dbd661326dfa6c46a5459b4c422d5d62c5c2372b",
          "sha1": "232e2cbc2b8e1311e1ee9f0788274df8c9e143a0",
          "md5": "8ff68b57029c6d2346631ee566845351"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "database-sqldelight-iosx64-0.23.0-sources.jar",
          "url": "database-sqldelight-iosx64-0.23.0-sources.jar",
          "size": 7611,
          "sha512": "c06d09453bf2e80c9279fa11b5eb4aaba4454dad14113d7c5b70df03ff6645c552acc0d4389976cbbee504737434706410692ff66662f64d43c836e58d8e6660",
          "sha256": "b7cd9808b029c66c0e854ed18479e3e86dfca7c42ee14a08f38f8bfc76767569",
          "sha1": "df597c129d52db901bc7729fc33edeeadb0b4773",
          "md5": "1ad1049ed75d2b7fce0480aa3d4f9092"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-database",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "database-sqldelight-iosx64-0.23.0-metadata.jar",
          "url": "database-sqldelight-iosx64-0.23.0-metadata.jar",
          "size": 2597,
          "sha512": "8230ae6ced9b2f76fb8ec6f4b2a751743db1c1e951d693685bfba24c64e9159f9a74113d9e4f52afb9877deb977013b7a269d2cadb1df155c7ac021050a7558b",
          "sha256": "83b2b10906aed161eaed33898a38f5560965e8b7bab0ffb22691df0134fe18d7",
          "sha1": "14a23801a862aebd18ee2750a5cae5cf93f02c72",
          "md5": "7cd2c51deec736bf0f9e342cfd8b997e"
        }
      ]
    }
  ]
}
