{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-preferences/0.24.2/core-preferences-0.24.2.module",
    "group": "dev.dexkot.mobile",
    "module": "core-preferences",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-preferences-release.aar",
          "url": "core-preferences-android-0.24.2.aar",
          "size": 3554,
          "sha512": "a500f8766cc202136976669b344afb97228a719f84c9fe806fb66536441cf7b9c2ee1370faadb0c3b4d1bce90a4bd649afb23b868c04f8e99e661fc3a2bee53d",
          "sha256": "800961ddc61ab1191ee496b2566e35293b85fd6355b9b15a5cf97aa435f7de85",
          "sha1": "55a42ac9edd4806c543fe52ada6ea2252f69fe05",
          "md5": "eb07335c769658b57ebd3b8fe34937b3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-preferences-release.aar",
          "url": "core-preferences-android-0.24.2.aar",
          "size": 3554,
          "sha512": "a500f8766cc202136976669b344afb97228a719f84c9fe806fb66536441cf7b9c2ee1370faadb0c3b4d1bce90a4bd649afb23b868c04f8e99e661fc3a2bee53d",
          "sha256": "800961ddc61ab1191ee496b2566e35293b85fd6355b9b15a5cf97aa435f7de85",
          "sha1": "55a42ac9edd4806c543fe52ada6ea2252f69fe05",
          "md5": "eb07335c769658b57ebd3b8fe34937b3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-preferences-android-0.24.2-sources.jar",
          "url": "core-preferences-android-0.24.2-sources.jar",
          "size": 3167,
          "sha512": "667311b4bb9b59953df8e9771381b953e453069b75c8a2b2b14fe456a8b1f6fb6911b2033da4f36574b2bad15d808c4b08be92608c5adfb51a7c256087c0da8f",
          "sha256": "88f8e9699a48e5bbd2b9ea0339046817e453ec6ead800388bb835c18027ffe33",
          "sha1": "55ef5cc2377140cc8960b059af5392c6a43a5521",
          "md5": "567233b2fb942a5f5ba0e85bf11e62fc"
        }
      ]
    }
  ]
}
