{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.20.0.jar",
          "url": "core-ksp-processor-0.20.0.jar",
          "size": 33243,
          "sha512": "d56629968e3b2e201ec79881bdf57820c1765a01fa1cf069de4d9dd96bfd513e20cfe170a94bef12428ff92637a08adef157a42f08b85a29e499d6f4464e395a",
          "sha256": "4d5296994a17c88c2a9ef7e26f7d12dd7aed61a578366861bce4427a26787e44",
          "sha1": "297dc7c60b408b684d5177401fe36cee969c021a",
          "md5": "ba9e42ed90a507aa3a7eb9628a1aaed4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.20.0.jar",
          "url": "core-ksp-processor-0.20.0.jar",
          "size": 33243,
          "sha512": "d56629968e3b2e201ec79881bdf57820c1765a01fa1cf069de4d9dd96bfd513e20cfe170a94bef12428ff92637a08adef157a42f08b85a29e499d6f4464e395a",
          "sha256": "4d5296994a17c88c2a9ef7e26f7d12dd7aed61a578366861bce4427a26787e44",
          "sha1": "297dc7c60b408b684d5177401fe36cee969c021a",
          "md5": "ba9e42ed90a507aa3a7eb9628a1aaed4"
        }
      ]
    }
  ]
}
