{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger-di-koin/0.27.0/core-logger-di-koin-0.27.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger-di-koin",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-di-koin-iosSimulatorArm64Main-0.27.0.klib",
          "url": "core-logger-di-koin-iossimulatorarm64-0.27.0.klib",
          "size": 6276,
          "sha512": "c80418d66f7a802816bf92ad9987fcb54e21860f9ba36f1d8c6386e8c241528f91af2296884bf6ea3150837e9026ec59ef1f53ef38e5ca23c0ec816798cd8eca",
          "sha256": "2368f4ec86880d3ddf1dff2ec965e0e28517bea6d2bb41174a1350f6cc579a71",
          "sha1": "993b274ca3fc619a9c6212d9d4b94f90d0a2727f",
          "md5": "707f04bf63bc493b1b74323f2ced4747"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-logger-di-koin-iossimulatorarm64-0.27.0-sources.jar",
          "url": "core-logger-di-koin-iossimulatorarm64-0.27.0-sources.jar",
          "size": 2287,
          "sha512": "1338703693fb1a6c4301e021619ed48199d94a4114428fab4470d01bfea4351ae46036142ce404e721b70a99afc9d4d2db6ed44d9edd3e736d3740f09d3c7bae",
          "sha256": "fcd782b1048fd9f658e704c1fbb5c411307a91e3f8c70cb6acbc0e1bac4dc976",
          "sha1": "13a4625d6400e608d13eac58cfd4f69664a8ef3e",
          "md5": "91c59ea784d016b7d08c04368268833c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-di-koin-iossimulatorarm64-0.27.0-metadata.jar",
          "url": "core-logger-di-koin-iossimulatorarm64-0.27.0-metadata.jar",
          "size": 261,
          "sha512": "449953c928ce3d2641c895f5761f3e0089d3c77582a99e469d5842b4c3e91e70f39a265ad598dbbc1ecc1bb0991c0ae37dd604821e341e8196cd902b342f24d3",
          "sha256": "f6d93dd7c0887ce82365477d3498c99180ea1699afc16289489cdf126944f295",
          "sha1": "74bda9334f75618181e454fa0367c5a2a4549fe4",
          "md5": "1534640ea12cda4200bc0be54f2ed605"
        }
      ]
    }
  ]
}
