{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig-posthog/0.23.0/core-remoteconfig-posthog-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-posthog",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "remoteconfig-posthog-release.aar",
          "url": "core-remoteconfig-posthog-android-0.23.0.aar",
          "size": 14049,
          "sha512": "3ed10a13c70998608183106c8bfeec501d596e7fc6ef8e4dd39e0842642201479ce1c5ba60064b5c50843f5b80956af33a3ad01ed60e7817791b1b876172f386",
          "sha256": "f77a71cbec3a6a33d73e51dc30d1efc8670229107c9582b9c00c64d512b65c06",
          "sha1": "0dc89ead023336a956b2ca5318f231da24e620ce",
          "md5": "77b2e1f93d2c1c4362082340c6656648"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.23.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "remoteconfig-posthog-release.aar",
          "url": "core-remoteconfig-posthog-android-0.23.0.aar",
          "size": 14049,
          "sha512": "3ed10a13c70998608183106c8bfeec501d596e7fc6ef8e4dd39e0842642201479ce1c5ba60064b5c50843f5b80956af33a3ad01ed60e7817791b1b876172f386",
          "sha256": "f77a71cbec3a6a33d73e51dc30d1efc8670229107c9582b9c00c64d512b65c06",
          "sha1": "0dc89ead023336a956b2ca5318f231da24e620ce",
          "md5": "77b2e1f93d2c1c4362082340c6656648"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remoteconfig-posthog-android-0.23.0-sources.jar",
          "url": "core-remoteconfig-posthog-android-0.23.0-sources.jar",
          "size": 5153,
          "sha512": "763a1edc8b69d307c8bbb4ef292311039d96926395871c7a0cf838dd44b0a3d758c23743f1e573dd7fb2b5107d91d8eff37ba5c470558cda4b134fdb35df589c",
          "sha256": "a8820c43e075b274aa9a70c0da7e070c4259c3bc10dd9b8466fd2e2032bdb6bc",
          "sha1": "1b39c6c044ab38696d4bc9244489325061fc2978",
          "md5": "dee8a2920a66e047ba5f2836eb1f3eb4"
        }
      ]
    }
  ]
}
