{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger-di-koin/0.25.0/core-logger-di-koin-0.25.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger-di-koin",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-di-koin-iosArm64Main-0.25.0.klib",
          "url": "core-logger-di-koin-iosarm64-0.25.0.klib",
          "size": 6210,
          "sha512": "664928a4cab1df27951cb77f220218f45d1dee8371066b366dc5a9c1d502b611606b143bd75499be3133b948e116453c291de5dae4275e2226888bef93fc8825",
          "sha256": "d277c9e4f3da4bb32d3dc2070e840ed3d420d6e6f961d93ad79b46364e4314dd",
          "sha1": "7601bb85804e811bb402cd9c19a7f4ca4d06fa32",
          "md5": "439641505a5d18c8415c4d6e1293f734"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-logger-di-koin-iosarm64-0.25.0-sources.jar",
          "url": "core-logger-di-koin-iosarm64-0.25.0-sources.jar",
          "size": 2287,
          "sha512": "1338703693fb1a6c4301e021619ed48199d94a4114428fab4470d01bfea4351ae46036142ce404e721b70a99afc9d4d2db6ed44d9edd3e736d3740f09d3c7bae",
          "sha256": "fcd782b1048fd9f658e704c1fbb5c411307a91e3f8c70cb6acbc0e1bac4dc976",
          "sha1": "13a4625d6400e608d13eac58cfd4f69664a8ef3e",
          "md5": "91c59ea784d016b7d08c04368268833c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-di-koin-iosarm64-0.25.0-metadata.jar",
          "url": "core-logger-di-koin-iosarm64-0.25.0-metadata.jar",
          "size": 261,
          "sha512": "a0c37f66007c3a732590e845727141d7925b22c337090a4634688c6d042b429ec23593692b357c4eb5b75fd8787b014a96b085ecf767099a1630f6d054fdaf4e",
          "sha256": "ffcaf13593a1f065d6ebc9d7b530650b4c5c4c5037d37aebb7697d20a569d416",
          "sha1": "91847e4d7c01380a2b2c8c055d0e97ac9ae40f13",
          "md5": "2c304184de884a7a87d1f006786a519d"
        }
      ]
    }
  ]
}
