{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-work/0.24.1/core-work-0.24.1.module",
    "group": "dev.dexkot.mobile",
    "module": "core-work",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-iosArm64Main-0.24.1.klib",
          "url": "core-work-iosarm64-0.24.1.klib",
          "size": 40039,
          "sha512": "aa843152c709a7bc307dd10274d83447d233f1f13c035508f26762677bea7d9c09aed14309a01f6ec5347949cb89c52689c8a4caf9b567eef38d2a66e458f07c",
          "sha256": "106f02c363539bd751f835169b4a68e8673bb6908362393a296db71681bdb716",
          "sha1": "e79be46bbf9eebcacab49757bbc6ee6d9a237bd1",
          "md5": "f93872da6c3cf9cc30ee2769a8f0f193"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-work-iosarm64-0.24.1-sources.jar",
          "url": "core-work-iosarm64-0.24.1-sources.jar",
          "size": 18515,
          "sha512": "68404b19ed1187697bd59dc943ad2e05226772004bad36ad4933fd8555b5576e1ae6596a1ade42366006de50e0f6b3a0c7f4a6440249fd8bd6f65a532ab8d352",
          "sha256": "14bb823510823f1fa170c49fe2876b94b636f26eb295a88a14fe3bc029d2d74b",
          "sha1": "a0906f3d1d58da4b786d774e26a0b952b220d6bb",
          "md5": "1c3dae832cc7d6b7d068ae414f662182"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-iosarm64-0.24.1-metadata.jar",
          "url": "core-work-iosarm64-0.24.1-metadata.jar",
          "size": 261,
          "sha512": "402bcf59875b1f98ebafa1090bb9bfcf111796df7d3d102d93c8c8d43e15d81fed0fc14c530435ef5f62a998f91b48712867db6c6382326c4365f3df817021f1",
          "sha256": "7d0f39d28ad525b617e20a4ecaec490234076f2fc91b9c9528da814af8a6db86",
          "sha1": "781ac2d0db5a9f7e7810e725cfe0f6124d8ebc8b",
          "md5": "f7766e23ae61321ff89f07a543af8221"
        }
      ]
    }
  ]
}
