{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.23.0/core-remoteconfig-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "remoteconfig-iosX64Main-0.23.0.klib",
          "url": "remoteconfig-iosx64-0.23.0.klib",
          "size": 16925,
          "sha512": "740f0771fe1ad3df553bbb2643c4d279b38fed5d28319a9cf08dab78c9d1dc831d5c81e984a981c2f6eb54b52efbe73c589e5f45583988687fe642b338818fa2",
          "sha256": "923dd11eb0f6b7365392e369ee8f943dadddbcd5a63b2d1d79f6dda4a4de9d66",
          "sha1": "d1af88dc58dfcf13feb78f8d5392e045b8651c9e",
          "md5": "6a96116954b4b1dcf8da757a4202274b"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "remoteconfig-iosx64-0.23.0-sources.jar",
          "url": "remoteconfig-iosx64-0.23.0-sources.jar",
          "size": 5911,
          "sha512": "80324a440ee63060b4ec2b7238516b6e191d40d41e5719093e2731b9b124ca1c0500be21264301227c132f7c840e291b6bcfcbe990e20d0230fb37fd91cec712",
          "sha256": "31c6b3dd523d0dfa8013d82c7080448dcb4621ebcbf25394f00ab957cf18863e",
          "sha1": "58b7aaf98ebce30a132bd2e82f05902727e98b86",
          "md5": "73fa0791cfbd433abc542059e2a5593b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "remoteconfig-iosx64-0.23.0-metadata.jar",
          "url": "remoteconfig-iosx64-0.23.0-metadata.jar",
          "size": 261,
          "sha512": "5f62f9c8fac0509109790b67508251e0ae3f2a0fb3ceceeaf5e70c4cd12be289fb608b637cd0c04f87188b9eade647a5f37b7abad477fa1ebf0fc4b04bd9e3c2",
          "sha256": "6fe5479f02a63bedb4c113d9da17897ada8f958358c591d5b566327e97d9ec6c",
          "sha1": "b3608ff2ceb93a504d95c3545a02a1541b6c3f30",
          "md5": "7fd5ba7d29ea7fcabe94ad9f506457c3"
        }
      ]
    }
  ]
}
