{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-database/0.16.0/core-database-0.16.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-database",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "database-release.aar",
          "url": "core-database-android-0.16.0.aar",
          "size": 5316,
          "sha512": "bc6b5ea028b6e959ef6240284cd159c13e7da478f56adcd4b299f1fca0c59affab8af1739803435654f290ce169ab3363e61bbb9acba5c03197a5a814b8a5a10",
          "sha256": "61d4f9bbeaecf017ba77284f66eaa48409e02686fdf47c19e41166bf1c9ab55a",
          "sha1": "d2165ee0622748a6169f5720b7fd425f5fd1ac7f",
          "md5": "731277ed5789ce4b9c009cc09b4933c7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.16.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-release.aar",
          "url": "core-database-android-0.16.0.aar",
          "size": 5316,
          "sha512": "bc6b5ea028b6e959ef6240284cd159c13e7da478f56adcd4b299f1fca0c59affab8af1739803435654f290ce169ab3363e61bbb9acba5c03197a5a814b8a5a10",
          "sha256": "61d4f9bbeaecf017ba77284f66eaa48409e02686fdf47c19e41166bf1c9ab55a",
          "sha1": "d2165ee0622748a6169f5720b7fd425f5fd1ac7f",
          "md5": "731277ed5789ce4b9c009cc09b4933c7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "database-android-0.16.0-sources.jar",
          "url": "core-database-android-0.16.0-sources.jar",
          "size": 2104,
          "sha512": "4490c10c602579a4558dadd16286df60598548bfc3080e3219a526e37db130140a319a4dda017d6124ec7f22799ce71059571723fc8fb30790f94f1f874e9f7d",
          "sha256": "aba816c8af3c5cd99718856e62b068ba054b269470163cda1b650ff6528fa9b3",
          "sha1": "d73da313d43e8ad8ab616ebec2906b0312caf837",
          "md5": "fcf5ff75f6c30576b4acf9df13f1e998"
        }
      ]
    }
  ]
}
