{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.15.0.jar",
          "url": "core-ksp-processor-0.15.0.jar",
          "size": 33243,
          "sha512": "c5d1b55da5ef2b1953023b3715722fad6836b81a3479506a8609825443f82be4570d9e596d0d702f61a13aeced1a32ca2aa7a2f61240ac3b8ac448145bcb7710",
          "sha256": "88958821f313121e42bef6616e2ba7fd6ace6411349144939f463ed425a7e7a9",
          "sha1": "300e411d7a2b4455d94ec5f40aeeb8de903c1689",
          "md5": "010d084887fb6074f969d4a173dc281a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.15.0.jar",
          "url": "core-ksp-processor-0.15.0.jar",
          "size": 33243,
          "sha512": "c5d1b55da5ef2b1953023b3715722fad6836b81a3479506a8609825443f82be4570d9e596d0d702f61a13aeced1a32ca2aa7a2f61240ac3b8ac448145bcb7710",
          "sha256": "88958821f313121e42bef6616e2ba7fd6ace6411349144939f463ed425a7e7a9",
          "sha1": "300e411d7a2b4455d94ec5f40aeeb8de903c1689",
          "md5": "010d084887fb6074f969d4a173dc281a"
        }
      ]
    }
  ]
}
