{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.8.0.jar",
          "url": "core-ksp-processor-0.8.0.jar",
          "size": 33242,
          "sha512": "b043af181cf7f6e5a2a5815d8b8261892d9ec7b0b46985ab46aad2e1c47a85b130749bba73971d87758fcaa73bc6e90aa645193951c08e7ffe2acf6f3ca323bb",
          "sha256": "5262370b6ac498063f8d03384b6fc0c60d632187a4349ed052af6626563f2286",
          "sha1": "d07d64ad4d8f2c5f14a345e6da7a4bbd636d4d59",
          "md5": "74ab264fc56e63316d0a20d58509b8d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.8.0.jar",
          "url": "core-ksp-processor-0.8.0.jar",
          "size": 33242,
          "sha512": "b043af181cf7f6e5a2a5815d8b8261892d9ec7b0b46985ab46aad2e1c47a85b130749bba73971d87758fcaa73bc6e90aa645193951c08e7ffe2acf6f3ca323bb",
          "sha256": "5262370b6ac498063f8d03384b6fc0c60d632187a4349ed052af6626563f2286",
          "sha1": "d07d64ad4d8f2c5f14a345e6da7a4bbd636d4d59",
          "md5": "74ab264fc56e63316d0a20d58509b8d7"
        }
      ]
    }
  ]
}
