{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-work/0.24.2/core-work-0.24.2.module",
    "group": "dev.dexkot.mobile",
    "module": "core-work",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-release.aar",
          "url": "core-work-android-0.24.2.aar",
          "size": 95151,
          "sha512": "fed23385d352871cb4d2e004b9c7d9cc931754a5d6cfc12153ae8000ce00ae7da98df57674558021fffeb19bd1041f7729cc816d184c322a74549b27038e4efa",
          "sha256": "ae9f93e64906af97edf14957920ad075c685a478892f418ac1be2731a1c73d8c",
          "sha1": "939c906d9c3296d094343cf78bd6d6d5cfd09782",
          "md5": "47767df9e853d8817824c0b4ebb09931"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.24.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-work-release.aar",
          "url": "core-work-android-0.24.2.aar",
          "size": 95151,
          "sha512": "fed23385d352871cb4d2e004b9c7d9cc931754a5d6cfc12153ae8000ce00ae7da98df57674558021fffeb19bd1041f7729cc816d184c322a74549b27038e4efa",
          "sha256": "ae9f93e64906af97edf14957920ad075c685a478892f418ac1be2731a1c73d8c",
          "sha1": "939c906d9c3296d094343cf78bd6d6d5cfd09782",
          "md5": "47767df9e853d8817824c0b4ebb09931"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-work-android-0.24.2-sources.jar",
          "url": "core-work-android-0.24.2-sources.jar",
          "size": 43363,
          "sha512": "c16c1b4d054e43bd37dbc385e5b0e44ba02a6e58a11f253567fd1862eeb88e1c6e10f13d2717d9ebf42e6e75dafd47536bda50b1298d654926ab5f660eb0eaba",
          "sha256": "d5b352a4f0b5aa45b8872ee247fb92e7418e86fee222c545d00758ab48a5d580",
          "sha1": "3f0a724c1fc12e47c08978f6c14a7d3b8e2cb8c5",
          "md5": "734612cbc69ce8241e5c089c3144950e"
        }
      ]
    }
  ]
}
