{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-0.8.0.aar",
          "url": "core-remoteconfig-0.8.0.aar",
          "size": 25620,
          "sha512": "75381b1593ac6c7df8daf7fb4efacea92af4545496a0e9b89067712010f41c8c62c1c7af4bfed44763772c9ddc65eba5ae31741550083b3a6106e52848f0f960",
          "sha256": "d7ceea2dc8aa47c630b0d68cc6a66998f94a25121c931bcf199b8e328d638e49",
          "sha1": "86c19a235f78bac21d4b671f2102a5ab1cf894b7",
          "md5": "8c90cda586c75585bc26b0bbe444fe74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-0.8.0.aar",
          "url": "core-remoteconfig-0.8.0.aar",
          "size": 25620,
          "sha512": "75381b1593ac6c7df8daf7fb4efacea92af4545496a0e9b89067712010f41c8c62c1c7af4bfed44763772c9ddc65eba5ae31741550083b3a6106e52848f0f960",
          "sha256": "d7ceea2dc8aa47c630b0d68cc6a66998f94a25121c931bcf199b8e328d638e49",
          "sha1": "86c19a235f78bac21d4b671f2102a5ab1cf894b7",
          "md5": "8c90cda586c75585bc26b0bbe444fe74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-remoteconfig-0.8.0-sources.jar",
          "url": "core-remoteconfig-0.8.0-sources.jar",
          "size": 4529,
          "sha512": "4f3a6f5f96eb1250fce967b9b90a2057fbea6044b69a2b0d9987923de494bcb56567dc8c655138544b52c8048fcd873b2e99894cb855759a45515fe5349c7da7",
          "sha256": "f84808b87d93ca1548b2685cd1c64aa90594d3feaeea1e16a3dcb708d7053bfd",
          "sha1": "19bd13e279592bbd8768b2703ea3737837a118c4",
          "md5": "4d526434a91e44509493f0ccf99f0883"
        }
      ]
    }
  ]
}
