{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-logger-posthog",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-posthog-metadata-0.23.0.jar",
          "url": "core-logger-posthog-0.23.0.jar",
          "size": 3315,
          "sha512": "72671e35359357ef838e9d845c52c2cfedc23b68450cffc13208e42903b2d74bab50eee9f0847a5b9fa6664f1b54cbb2f3672196044022fa001e6f32ca3eebf8",
          "sha256": "4fd0cbd796195eaeea46695f49b3ce5ae80010f0bc851beb4cdc9d4de9a1100c",
          "sha1": "d434aab5f7997bbb4cd7d3b6f7492da7924dfcce",
          "md5": "4c7b3a335b6a4aa1786cbd417712cc47"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "logger-posthog-kotlin-0.23.0-sources.jar",
          "url": "core-logger-posthog-0.23.0-sources.jar",
          "size": 4829,
          "sha512": "988ea5c885fec5aa2277388106850ba12129eef4abec3b058754d2398da90d6c5d8e246c26075097b28a25945e3412b88f9f28fcb82cc763cfa1507bb7b063a7",
          "sha256": "415d4650aca17b6ba1bb8c4cd527e8553796205df2a25fddf7ddd4644ca95d2e",
          "sha1": "2f4976d94ae0c5f159c923f27081ea6cb8298cdf",
          "md5": "250e515186543606ba0e9c901fda9655"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-posthog-android/0.23.0/core-logger-posthog-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-posthog-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-posthog-android/0.23.0/core-logger-posthog-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-posthog-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-posthog-android/0.23.0/core-logger-posthog-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-posthog-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iosarm64/0.23.0/logger-posthog-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iosarm64/0.23.0/logger-posthog-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iosarm64/0.23.0/logger-posthog-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iossimulatorarm64/0.23.0/logger-posthog-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iossimulatorarm64/0.23.0/logger-posthog-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iossimulatorarm64/0.23.0/logger-posthog-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iosx64/0.23.0/logger-posthog-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iosx64/0.23.0/logger-posthog-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-posthog-iosx64/0.23.0/logger-posthog-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-posthog-iosx64",
        "version": "0.23.0"
      }
    }
  ]
}
