{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger-firebase/0.26.0/core-logger-firebase-0.26.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger-firebase",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-firebase-release.aar",
          "url": "core-logger-firebase-android-0.26.0.aar",
          "size": 7636,
          "sha512": "d20ad616ba1d6cebdc7fafa5dad9ddaa4aa226b2f3113725ac2eb01326ecbceca99d6c78f3951824e06a2d471df3f6a48589d89780056b39a21c51c2d286eb04",
          "sha256": "87062d357fb4e4ecc0b4aa4ee762e90de45733eb8481dd29416fce12a23ad46c",
          "sha1": "ee9d6874a475253c55fb21e4650bb9d412ceb923",
          "md5": "9b2a5eeba7da5676c51a93306c6dbd32"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.26.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-logger-firebase-release.aar",
          "url": "core-logger-firebase-android-0.26.0.aar",
          "size": 7636,
          "sha512": "d20ad616ba1d6cebdc7fafa5dad9ddaa4aa226b2f3113725ac2eb01326ecbceca99d6c78f3951824e06a2d471df3f6a48589d89780056b39a21c51c2d286eb04",
          "sha256": "87062d357fb4e4ecc0b4aa4ee762e90de45733eb8481dd29416fce12a23ad46c",
          "sha1": "ee9d6874a475253c55fb21e4650bb9d412ceb923",
          "md5": "9b2a5eeba7da5676c51a93306c6dbd32"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-logger-firebase-android-0.26.0-sources.jar",
          "url": "core-logger-firebase-android-0.26.0-sources.jar",
          "size": 4034,
          "sha512": "70509198c4725ee8b4f139df85e97215ccd3d6265da68cc41b775c003ac3df53e3b630465df4d26c04d0c3e0f8bc5d300fe4ed510630283089ddf5866bb8856e",
          "sha256": "bdcf069dbd3bad8a7333e8c32c760d8396c7791f3764610e8855f873e7e65db9",
          "sha1": "94ae716ad3fc5041f83d3e3f2c0b7d2f63094473",
          "md5": "6afcdc6470ff9111cd6544b6e494a49f"
        }
      ]
    }
  ]
}
