{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger/0.23.0/core-logger-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "logger-iosX64Main-0.23.0.klib",
          "url": "logger-iosx64-0.23.0.klib",
          "size": 63110,
          "sha512": "d678162aa111962f80f4e65562daa186d0cee306e17987ed3a9560f633ed8255b453312e5231dad015c99f5ab805c05e59fec987859b59dd98ea4fd74df36849",
          "sha256": "eeac9248800ddf08c248158e5bb8ef66c1a521c2cd8f23b2de537be049e8d312",
          "sha1": "8e8dec52527d9c076f165f30232690ca29fd97d6",
          "md5": "f43fe378119d90540c22f43a3b42c307"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "logger-iosx64-0.23.0-sources.jar",
          "url": "logger-iosx64-0.23.0-sources.jar",
          "size": 23929,
          "sha512": "063dd56f60de910c07137f78ea6f157e3ee8477b7d76bc8b760ced901ad3a8361f9bc8966de424abcdb0d14012e5954171423a4f2f264f2042acee7b14b77869",
          "sha256": "6c8953055122a44d7eab85cdcd9d8f7c5c0d8809a05b3f45409624880819ea44",
          "sha1": "6bcf5e625931b3a117ba7ac205709a182b8013eb",
          "md5": "c457ec00f07b10a0da189f10e77a348b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "logger-iosx64-0.23.0-metadata.jar",
          "url": "logger-iosx64-0.23.0-metadata.jar",
          "size": 4211,
          "sha512": "7300e2d5dc07bbe1c5ab3ad1927bb5b86cb76ea695da3a63cf1f544e55f294af8332fd425a40db5a687d746a8e32f36de3657b3ef3fe089d4e92b6e2d1d34066",
          "sha256": "3b2c595a1085a94c2fd793f57b101dd3b8df6fa70b94229975c5a8c517cba6fe",
          "sha1": "caf715956e0046209c0ef6c0dfd2c2fea547a2bb",
          "md5": "72577a13f6685e658a3ca113baa613ea"
        }
      ]
    }
  ]
}
