{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.3.0.jar",
          "url": "core-ksp-processor-0.3.0.jar",
          "size": 33242,
          "sha512": "0d270596a24ce1c83865924a148c45ce88fc00d99c55b143c9c1fa1e471873ecf53228465b10201fa619a16540c8859605234e56bd80327401ea2d90f29f58f5",
          "sha256": "a5bf58b7b0a2f3b783b9272e13ff37fd04913eaeaa432933ac70438e47ff0bf2",
          "sha1": "045b3da2b8b0b643ce6212d320762ba73b84cb0a",
          "md5": "fe2285269a69d7d96cc47b35ffe24432"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.3.0.jar",
          "url": "core-ksp-processor-0.3.0.jar",
          "size": 33242,
          "sha512": "0d270596a24ce1c83865924a148c45ce88fc00d99c55b143c9c1fa1e471873ecf53228465b10201fa619a16540c8859605234e56bd80327401ea2d90f29f58f5",
          "sha256": "a5bf58b7b0a2f3b783b9272e13ff37fd04913eaeaa432933ac70438e47ff0bf2",
          "sha1": "045b3da2b8b0b643ce6212d320762ba73b84cb0a",
          "md5": "fe2285269a69d7d96cc47b35ffe24432"
        }
      ]
    }
  ]
}
