{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-posthog",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "remoteconfig-posthog-metadata-0.23.0.jar",
          "url": "core-remoteconfig-posthog-0.23.0.jar",
          "size": 3716,
          "sha512": "7b0cec7958370f1ca75a1dcdab774d33643d4eae85e5a46acc88cc16b1c64f9b6bdb602161eff741f27cd2604dd9ebe5c7b748722eebb82bece76a079a24cf7f",
          "sha256": "30e1f83caa5c53a8c929a72d35d3ce2615790e0619b4ebb1485e92ade77fe5a8",
          "sha1": "9d8fc964e1f9b211e7158c4feed7a0239fe12b56",
          "md5": "9fb7e5128da2e975787cb00ac9e4e389"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "remoteconfig-posthog-kotlin-0.23.0-sources.jar",
          "url": "core-remoteconfig-posthog-0.23.0-sources.jar",
          "size": 5224,
          "sha512": "68cf15cb7eff57061eeae3ed039b75387f4cae292645196353e5954e4066bcff5fbe881f7522de9109ad18e5570fd55b25c5db668823957f0cb0571f84624d8c",
          "sha256": "e2ec8150b4e18429e3d17d3ff4d59cf7316e1c6964a31711f7064571b8f440a0",
          "sha1": "8978ebcffa9c9b0fcb8f8e6f96417079ecc57d58",
          "md5": "3939358f2dbd6b7c6ca1c830b5b42baf"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-remoteconfig-posthog-android/0.23.0/core-remoteconfig-posthog-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-remoteconfig-posthog-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-remoteconfig-posthog-android/0.23.0/core-remoteconfig-posthog-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-remoteconfig-posthog-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-remoteconfig-posthog-android/0.23.0/core-remoteconfig-posthog-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-remoteconfig-posthog-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iosarm64/0.23.0/remoteconfig-posthog-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iosarm64/0.23.0/remoteconfig-posthog-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iosarm64/0.23.0/remoteconfig-posthog-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iossimulatorarm64/0.23.0/remoteconfig-posthog-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iossimulatorarm64/0.23.0/remoteconfig-posthog-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iossimulatorarm64/0.23.0/remoteconfig-posthog-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iosx64/0.23.0/remoteconfig-posthog-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iosx64/0.23.0/remoteconfig-posthog-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-posthog-iosx64/0.23.0/remoteconfig-posthog-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-posthog-iosx64",
        "version": "0.23.0"
      }
    }
  ]
}
