{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-preferences",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-preferences-metadata-0.24.2.jar",
          "url": "core-preferences-0.24.2.jar",
          "size": 2434,
          "sha512": "e06adedac3dfcc1f3f08a6db44ba519810f9633007e60d8656f17f7a623cbfe507741e8213b8ee92880a1848c0e9ccd2e208c0efce3f40cf4c322bbaebf61514",
          "sha256": "25197e3a347b8a0a784e1796778b6ac19e04d3d0ae3162df0eeb9b8ece3b31ef",
          "sha1": "48ded9cec0cf9d43fc7e6c11377c2aa8dfd83e42",
          "md5": "459e1e22aebf3ee84762e913ffcdbee5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-preferences-kotlin-0.24.2-sources.jar",
          "url": "core-preferences-0.24.2-sources.jar",
          "size": 3078,
          "sha512": "3a841e86abfb84b998b6184dc238e3bdeea6f0532fd601d6eef9994e39b2a0783c7dfb6552b75995d23aaefdb99d4d6c100ff564a420f3fccb10492a9b35f145",
          "sha256": "7cd355c9e11881a83e0a74e6e4984558b37113522e56051a09eae960484a09fe",
          "sha1": "e2131093f190a5917637ae172a3ae525579c2a24",
          "md5": "d0fd20285e39a5ea0c4c702a4778b352"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-preferences-android/0.24.2/core-preferences-android-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-android",
        "version": "0.24.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-preferences-android/0.24.2/core-preferences-android-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-android",
        "version": "0.24.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-preferences-android/0.24.2/core-preferences-android-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-android",
        "version": "0.24.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-preferences-iosarm64/0.24.2/core-preferences-iosarm64-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-iosarm64",
        "version": "0.24.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-preferences-iosarm64/0.24.2/core-preferences-iosarm64-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-iosarm64",
        "version": "0.24.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-preferences-iosarm64/0.24.2/core-preferences-iosarm64-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-iosarm64",
        "version": "0.24.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-preferences-iossimulatorarm64/0.24.2/core-preferences-iossimulatorarm64-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-iossimulatorarm64",
        "version": "0.24.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-preferences-iossimulatorarm64/0.24.2/core-preferences-iossimulatorarm64-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-iossimulatorarm64",
        "version": "0.24.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-preferences-iossimulatorarm64/0.24.2/core-preferences-iossimulatorarm64-0.24.2.module",
        "group": "dev.dexkot.mobile",
        "module": "core-preferences-iossimulatorarm64",
        "version": "0.24.2"
      }
    }
  ]
}
