{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.4.0.jar",
          "url": "core-ksp-processor-0.4.0.jar",
          "size": 33242,
          "sha512": "ae2089b4e219896b94ac1e2a90a37f8f925c398cd46f0b3a538f741359592c45c01dd2e12505f007055d018829af19375e3c46c5032e37e85bf56edf26448402",
          "sha256": "407582190e5f005b37f2da1be4c74a07b7bef1114704e1dadc5b3d72e36705a8",
          "sha1": "5097f323bf7e47397f77574ac4d3444426c7d3e4",
          "md5": "ec165eda0d56a47fbf6764fbbae0ae22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.4.0.jar",
          "url": "core-ksp-processor-0.4.0.jar",
          "size": 33242,
          "sha512": "ae2089b4e219896b94ac1e2a90a37f8f925c398cd46f0b3a538f741359592c45c01dd2e12505f007055d018829af19375e3c46c5032e37e85bf56edf26448402",
          "sha256": "407582190e5f005b37f2da1be4c74a07b7bef1114704e1dadc5b3d72e36705a8",
          "sha1": "5097f323bf7e47397f77574ac4d3444426c7d3e4",
          "md5": "ec165eda0d56a47fbf6764fbbae0ae22"
        }
      ]
    }
  ]
}
