{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-foundation/0.23.0/core-foundation-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-iosArm64Main-0.23.0.klib",
          "url": "foundation-iosarm64-0.23.0.klib",
          "size": 19947,
          "sha512": "c9d180b4d24997e5fe7085d5d21c838f05f420820383550b750a2cae8b3dc45159f8a220046aeac8d36552469f62a6f797b12acfbb3d5acbc36112a0e7777c14",
          "sha256": "0f91107a834b21b942fc0ab363ffeeb09765aa71f5edf9fb4093bba16c5eed68",
          "sha1": "05bab1b71483fa91deca2db4a908fc22d45347bf",
          "md5": "9434c236ce6a9fd8451e32a6fcd4b085"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "foundation-iosarm64-0.23.0-sources.jar",
          "url": "foundation-iosarm64-0.23.0-sources.jar",
          "size": 8352,
          "sha512": "0a3155ab9a019942a9596b6b9a27c0bc357fa35fc5436ca3c1727d8944fdd048eb701595367b685c8ebccaa773c2e5e57aa59efa3a2e92f9e989ea47893409fa",
          "sha256": "dbc0a12fa4085fdfec1b8fd3e1455f0ce094ca2ad2a8b1dbf43b7db37232ea05",
          "sha1": "aaeab93d8e84d936c9dfb525d9297c81875b2015",
          "md5": "56ad5c23ad0c8f011974082234440dcd"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-iosarm64-0.23.0-metadata.jar",
          "url": "foundation-iosarm64-0.23.0-metadata.jar",
          "size": 2424,
          "sha512": "25170a94ec44c1d40c5fec2cf44d41a9ecb527c2c440c10ac25fa464eb29a65a2e6518db2d501048720bcd24611e968ad67a0f99c580cf453c55a6f47b67a7a6",
          "sha256": "d30ef54b71b7bde2eca89e473c645887fd7626f15264acda86c303deec60fa90",
          "sha1": "d08fa75b07bcbd3d8f5bf6a53922abbdbc0e3673",
          "md5": "06d3d12d9a14a6fc762d720c797e5826"
        }
      ]
    }
  ]
}
