{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger-di-koin/0.25.0/core-logger-di-koin-0.25.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger-di-koin",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-di-koin-iosSimulatorArm64Main-0.25.0.klib",
          "url": "core-logger-di-koin-iossimulatorarm64-0.25.0.klib",
          "size": 6276,
          "sha512": "c80418d66f7a802816bf92ad9987fcb54e21860f9ba36f1d8c6386e8c241528f91af2296884bf6ea3150837e9026ec59ef1f53ef38e5ca23c0ec816798cd8eca",
          "sha256": "2368f4ec86880d3ddf1dff2ec965e0e28517bea6d2bb41174a1350f6cc579a71",
          "sha1": "993b274ca3fc619a9c6212d9d4b94f90d0a2727f",
          "md5": "707f04bf63bc493b1b74323f2ced4747"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-logger-di-koin-iossimulatorarm64-0.25.0-sources.jar",
          "url": "core-logger-di-koin-iossimulatorarm64-0.25.0-sources.jar",
          "size": 2287,
          "sha512": "1338703693fb1a6c4301e021619ed48199d94a4114428fab4470d01bfea4351ae46036142ce404e721b70a99afc9d4d2db6ed44d9edd3e736d3740f09d3c7bae",
          "sha256": "fcd782b1048fd9f658e704c1fbb5c411307a91e3f8c70cb6acbc0e1bac4dc976",
          "sha1": "13a4625d6400e608d13eac58cfd4f69664a8ef3e",
          "md5": "91c59ea784d016b7d08c04368268833c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-di-koin-iossimulatorarm64-0.25.0-metadata.jar",
          "url": "core-logger-di-koin-iossimulatorarm64-0.25.0-metadata.jar",
          "size": 261,
          "sha512": "a0c37f66007c3a732590e845727141d7925b22c337090a4634688c6d042b429ec23593692b357c4eb5b75fd8787b014a96b085ecf767099a1630f6d054fdaf4e",
          "sha256": "ffcaf13593a1f065d6ebc9d7b530650b4c5c4c5037d37aebb7697d20a569d416",
          "sha1": "91847e4d7c01380a2b2c8c055d0e97ac9ae40f13",
          "md5": "2c304184de884a7a87d1f006786a519d"
        }
      ]
    }
  ]
}
