{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-di-koin",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.23.0.aar",
          "url": "core-di-koin-0.23.0.aar",
          "size": 24190,
          "sha512": "58e9611cbdb29bfae97dcd0c786ddbe8153ee69abb6244b24395552c009b1c5abbb5f516087dbd1db2c9762cbf022eccffa7be873d66846d9a026b4645977200",
          "sha256": "8be2aeae253f2046a9ffb3835407551ac9d3a90bd788d449434e1d57b2ec78ff",
          "sha1": "d39e7924c66ed24beed11ff72f7387a164f7dd59",
          "md5": "d0b5effb5e29f1c5da11c7508d72aadc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-work",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.23.0.aar",
          "url": "core-di-koin-0.23.0.aar",
          "size": 24190,
          "sha512": "58e9611cbdb29bfae97dcd0c786ddbe8153ee69abb6244b24395552c009b1c5abbb5f516087dbd1db2c9762cbf022eccffa7be873d66846d9a026b4645977200",
          "sha256": "8be2aeae253f2046a9ffb3835407551ac9d3a90bd788d449434e1d57b2ec78ff",
          "sha1": "d39e7924c66ed24beed11ff72f7387a164f7dd59",
          "md5": "d0b5effb5e29f1c5da11c7508d72aadc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-di-koin-0.23.0-sources.jar",
          "url": "core-di-koin-0.23.0-sources.jar",
          "size": 5650,
          "sha512": "f14104fca77c531f162002f65d1fed9c4fb287cc7e56b2bc1dc16fd42d8b582c579f36ca6f84568410dde45d9d5de53f4ffc7c951606ac531814b654d4cc8a96",
          "sha256": "f1125a47b7367d0bb3dc835eafe14ca1d8e2b9d7f411e0a4ac847d409f79da90",
          "sha1": "b2381926d56a6e5b1a2d74dca8f7a17804af0a7a",
          "md5": "3215bb4bc91b7482cdd969dffdb1a53f"
        }
      ]
    }
  ]
}
