{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig-posthog/0.24.1/core-remoteconfig-posthog-0.24.1.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-posthog",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-release.aar",
          "url": "core-remoteconfig-posthog-android-0.24.1.aar",
          "size": 14075,
          "sha512": "38767f0332dd0ae74bc79aa630ef651479a82c06fcd33cd320c77fd85e88ae9e097d649c536468e6febefcaed53c2110b153dfb3d7b744821d5aef1a14d81e0d",
          "sha256": "d7eec2a4b6a7272181f93e18b1ee5227169a1ca91b3155affb95794c7df48a78",
          "sha1": "384c9b97a0b4a02669c7937ead61eedde8f27484",
          "md5": "c0ea5b38fb79500921649a47ab71e695"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.24.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-release.aar",
          "url": "core-remoteconfig-posthog-android-0.24.1.aar",
          "size": 14075,
          "sha512": "38767f0332dd0ae74bc79aa630ef651479a82c06fcd33cd320c77fd85e88ae9e097d649c536468e6febefcaed53c2110b153dfb3d7b744821d5aef1a14d81e0d",
          "sha256": "d7eec2a4b6a7272181f93e18b1ee5227169a1ca91b3155affb95794c7df48a78",
          "sha1": "384c9b97a0b4a02669c7937ead61eedde8f27484",
          "md5": "c0ea5b38fb79500921649a47ab71e695"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-remoteconfig-posthog-android-0.24.1-sources.jar",
          "url": "core-remoteconfig-posthog-android-0.24.1-sources.jar",
          "size": 5153,
          "sha512": "763a1edc8b69d307c8bbb4ef292311039d96926395871c7a0cf838dd44b0a3d758c23743f1e573dd7fb2b5107d91d8eff37ba5c470558cda4b134fdb35df589c",
          "sha256": "a8820c43e075b274aa9a70c0da7e070c4259c3bc10dd9b8466fd2e2032bdb6bc",
          "sha1": "1b39c6c044ab38696d4bc9244489325061fc2978",
          "md5": "dee8a2920a66e047ba5f2836eb1f3eb4"
        }
      ]
    }
  ]
}
