{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-foundation-0.1.0.aar",
          "url": "core-foundation-0.1.0.aar",
          "size": 28481,
          "sha512": "cd1dfbed482410d1bf65e99aa66268a0c77962774e501c8c31bb419fd231091512607e92c62346dd94eb95430a3a3339997073b854ceb9fab789ca940cb640b9",
          "sha256": "7c7c5999240fdd1fc7da4ea402375426274d69f235c1c6f2665ef82adf82de7b",
          "sha1": "8b6ea40476f78eb7dbc1441f05f437fcc23de9fa",
          "md5": "6cc20f67a75fd09c58295ffa19cfc03b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-foundation-0.1.0.aar",
          "url": "core-foundation-0.1.0.aar",
          "size": 28481,
          "sha512": "cd1dfbed482410d1bf65e99aa66268a0c77962774e501c8c31bb419fd231091512607e92c62346dd94eb95430a3a3339997073b854ceb9fab789ca940cb640b9",
          "sha256": "7c7c5999240fdd1fc7da4ea402375426274d69f235c1c6f2665ef82adf82de7b",
          "sha1": "8b6ea40476f78eb7dbc1441f05f437fcc23de9fa",
          "md5": "6cc20f67a75fd09c58295ffa19cfc03b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-foundation-0.1.0-sources.jar",
          "url": "core-foundation-0.1.0-sources.jar",
          "size": 8707,
          "sha512": "23af402dae4f96e2960b2540dccdd6ac57a8b06ae1e8e28af17f50589a397eadd2973dfb1d87dd4a4080a632ba96c7026e552693a5963f6acdf7f9df12514867",
          "sha256": "20e6dc5976624a970f67434ac81a53dc81e0ee0f6cecddc3789d4dd6298b3815",
          "sha1": "14ad0f26a3875d2db9a7557c1c30e9c7cb10555e",
          "md5": "e695e24984e71dd0031ade671fd91f15"
        }
      ]
    }
  ]
}
