{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-di-koin",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.19.0.aar",
          "url": "core-di-koin-0.19.0.aar",
          "size": 24666,
          "sha512": "4adcfc971676d5e651df81fdc5886b3c81a59f0d7f66fb547b3f684919af8b914d72447ae2e70e233e67f94ec727b935232f9fdcc0814752156430940a353afc",
          "sha256": "a796cf1f31e8a4c18c14c0e5d871b85329f1dc162664c8d4832761e01a7580fa",
          "sha1": "6279b182d0e0a217d3a079bee4d72dcb916e4d8e",
          "md5": "eaecfcae04faa9316c0f242c0b21636f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-work",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.19.0.aar",
          "url": "core-di-koin-0.19.0.aar",
          "size": 24666,
          "sha512": "4adcfc971676d5e651df81fdc5886b3c81a59f0d7f66fb547b3f684919af8b914d72447ae2e70e233e67f94ec727b935232f9fdcc0814752156430940a353afc",
          "sha256": "a796cf1f31e8a4c18c14c0e5d871b85329f1dc162664c8d4832761e01a7580fa",
          "sha1": "6279b182d0e0a217d3a079bee4d72dcb916e4d8e",
          "md5": "eaecfcae04faa9316c0f242c0b21636f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-di-koin-0.19.0-sources.jar",
          "url": "core-di-koin-0.19.0-sources.jar",
          "size": 5781,
          "sha512": "3b707706557b9883522456aee5c4e3524b5a6763817d0bf1c8477c43acb69814d3466a8dcf0f677349fe00322b0e754115587fe67e59a60beb9b36325fe2e6b4",
          "sha256": "cd3a1e6b08fda0bc06cd692ed834c318b988be0d0c3ad31f675a53b3db260213",
          "sha1": "35e348e3b4a209e64ddb9a8ba96fdff91adf068b",
          "md5": "27ba278310bd2a0c2b12115eef52878b"
        }
      ]
    }
  ]
}
