{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-work",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "work-metadata-0.22.0.jar",
          "url": "core-work-0.22.0.jar",
          "size": 16605,
          "sha512": "c9c73ab2438f7c95e3e6ecc880b5be326846d53012befe1d12a42457e06a3ff1cdf43fd4d97718edb145c2c05ad2893cefff80d0129626b1fe0e4ae72a18481a",
          "sha256": "bd293bef919dad6e9c761710b8c8ad9c4493e9207faa0f6278f50674b9b71988",
          "sha1": "9f5eba09109082945f2606760861f15b2deb2ea3",
          "md5": "1b61def093833858dc64d60940265281"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "work-kotlin-0.22.0-sources.jar",
          "url": "core-work-0.22.0-sources.jar",
          "size": 18515,
          "sha512": "68404b19ed1187697bd59dc943ad2e05226772004bad36ad4933fd8555b5576e1ae6596a1ade42366006de50e0f6b3a0c7f4a6440249fd8bd6f65a532ab8d352",
          "sha256": "14bb823510823f1fa170c49fe2876b94b636f26eb295a88a14fe3bc029d2d74b",
          "sha1": "a0906f3d1d58da4b786d774e26a0b952b220d6bb",
          "md5": "1c3dae832cc7d6b7d068ae414f662182"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.22.0/core-work-android-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.22.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.22.0/core-work-android-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.22.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.22.0/core-work-android-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosarm64/0.22.0/work-iosarm64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosarm64/0.22.0/work-iosarm64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosarm64/0.22.0/work-iosarm64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iossimulatorarm64/0.22.0/work-iossimulatorarm64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iossimulatorarm64/0.22.0/work-iossimulatorarm64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iossimulatorarm64/0.22.0/work-iossimulatorarm64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosx64/0.22.0/work-iosx64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosx64/0.22.0/work-iosx64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosx64/0.22.0/work-iosx64-0.22.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosx64",
        "version": "0.22.0"
      }
    }
  ]
}
