{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ui-di-koin",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-di-koin-0.26.0.aar",
          "url": "core-ui-di-koin-0.26.0.aar",
          "size": 4723,
          "sha512": "def9e20c9afa9c9a01ea9f698bbd96e0f4d69d1c637a910ff4780c4014167613d372930c77bff12b28b8cca679514398a084f5bf85b7e59849b45629287a1010",
          "sha256": "86c7c5811ac8b666dfdd0fbce736f8256e6d76e708cdfa21e2f04026cd7c5d67",
          "sha1": "4046bece41d1eca05184f224d9ebdf0c3e3804a1",
          "md5": "c13a9418e45397439381c2377156a22d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-di-koin-0.26.0.aar",
          "url": "core-ui-di-koin-0.26.0.aar",
          "size": 4723,
          "sha512": "def9e20c9afa9c9a01ea9f698bbd96e0f4d69d1c637a910ff4780c4014167613d372930c77bff12b28b8cca679514398a084f5bf85b7e59849b45629287a1010",
          "sha256": "86c7c5811ac8b666dfdd0fbce736f8256e6d76e708cdfa21e2f04026cd7c5d67",
          "sha1": "4046bece41d1eca05184f224d9ebdf0c3e3804a1",
          "md5": "c13a9418e45397439381c2377156a22d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ui-di-koin-0.26.0-sources.jar",
          "url": "core-ui-di-koin-0.26.0-sources.jar",
          "size": 1766,
          "sha512": "36e3cdce4a98a993e676f7d2616932ee5747a76001e6a091686d0053f5fdc58d1785ebc984d299564f807182268bd0fc2d42a882496657be07cd4af6e1cf7ab7",
          "sha256": "6e976551c289d1f2a3fb906d55493c3d79471f20fe8eaea74b8379517bcc92ba",
          "sha1": "2a3560b68f88e7c500bb9983e933ea98a6c748eb",
          "md5": "befd4591a6d07bfa26e2969cece6a429"
        }
      ]
    }
  ]
}
