{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger-posthog/0.24.1/core-logger-posthog-0.24.1.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger-posthog",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-posthog-iosSimulatorArm64Main-0.24.1.klib",
          "url": "core-logger-posthog-iossimulatorarm64-0.24.1.klib",
          "size": 16175,
          "sha512": "6cdb722647f0c7f2807eb7f8fda80fbd72372ae5c1409298d2b3ae38ef2f9a1e60f00d5a714dcf2b4399e0851b2cf54ce5318543e4cfe60e02cd88fb82c3390e",
          "sha256": "1b48512a0537f8ee0d0c9ce62f3f1c5f989ca51174c6a497413432186a5a8a5e",
          "sha1": "506ca44215e04d39a01f75b3bf2a4e23597f680c",
          "md5": "55d3768039f368aa7a69e67d76dbec17"
        },
        {
          "name": "core-logger-posthog-iosSimulatorArm64Cinterop-PostHogMain-0.24.1.klib",
          "url": "core-logger-posthog-iossimulatorarm64-0.24.1-cinterop-PostHog.klib",
          "size": 21196,
          "sha512": "be4328022f944dfe590df3ad631b1f8f35839dbb55d4d27a0557f23b1a321698881159a948ffee74a3272c82f963306fe0584be278aeac10652765702fede087",
          "sha256": "5ac5a7ce00d3cd7bc965a6864977e90fff94b6bfb6ca38cbdfbc437273f283aa",
          "sha1": "0489c2484120a6979688531ba5978f2c37180217",
          "md5": "de359524dd83ec013dcc4b9c11cfbef0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-logger-posthog-iossimulatorarm64-0.24.1-sources.jar",
          "url": "core-logger-posthog-iossimulatorarm64-0.24.1-sources.jar",
          "size": 4829,
          "sha512": "1edd1960e779ecc921a52c9182b0efdbe6b4e1655aaa0afab2efe1547ef045945543105dc42715c85c3fcf8fced5de59f6ebfafb827a0b533777dfde18888014",
          "sha256": "f010b1e679e6428e381b97eb825ed808dcf592b90946444494178256ce5e069f",
          "sha1": "39b2a8f0ba5bedad80a8187291732ee43dc0b539",
          "md5": "cf1702f80ca814c1310ddd80cff05705"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-posthog-iossimulatorarm64-0.24.1-metadata.jar",
          "url": "core-logger-posthog-iossimulatorarm64-0.24.1-metadata.jar",
          "size": 55964,
          "sha512": "869eecfbef03cbd7ced132115c7828352b9909e5804ea87ba5de23520583bbab55fcbec265138d2e52c4d8864b0854decdee40be5e4d3ded5e44fb931faa5db5",
          "sha256": "bb6cccc5ca5c6836ef1eae174d4ed6e1c67a92e51f9786a1aa33afcf1fe6f1de",
          "sha1": "d5496556b41c883c551e35a288d38fa20a157b00",
          "md5": "1e5426732601a007f8bf3f96df196d5e"
        }
      ]
    }
  ]
}
