{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.27.0.jar",
          "url": "core-ksp-processor-0.27.0.jar",
          "size": 33575,
          "sha512": "5ba14da0219414eb8bd8bd1542fb459ab38f4d5f17028e50b5a87a4dcc76dbb1eba53ef5144ae8c4e4fffd4e8564dd17ab180cd78bd28d99705abe6c6dc6b1e5",
          "sha256": "9ac06c322401bfb5caeec1f7f44134b8cbe33b45cdb5de1b762bd77d0cd01030",
          "sha1": "09af88951afe981d3d1e2e651c7b11ba6bad6e98",
          "md5": "669ca827ae4006e4c6a48c4441b62f0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.27.0.jar",
          "url": "core-ksp-processor-0.27.0.jar",
          "size": 33575,
          "sha512": "5ba14da0219414eb8bd8bd1542fb459ab38f4d5f17028e50b5a87a4dcc76dbb1eba53ef5144ae8c4e4fffd4e8564dd17ab180cd78bd28d99705abe6c6dc6b1e5",
          "sha256": "9ac06c322401bfb5caeec1f7f44134b8cbe33b45cdb5de1b762bd77d0cd01030",
          "sha1": "09af88951afe981d3d1e2e651c7b11ba6bad6e98",
          "md5": "669ca827ae4006e4c6a48c4441b62f0e"
        }
      ]
    }
  ]
}
