{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ui",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.25.0.aar",
          "url": "core-ui-0.25.0.aar",
          "size": 164754,
          "sha512": "262f5545e954510d55b645a53eeb980d8d4dc5ca8b60833a800301f2fe725fadc8192b19d0383c7a0d33b7f58bb2b923faacb341f0299280535e33fc93d6ddc5",
          "sha256": "63b5a4251fa3cce5310cb6e2cff4a91e3b99e3c8d3dce0160db940fb3e43d185",
          "sha1": "4b1467cd56fef3e0ef161c9407790c4e71a51248",
          "md5": "5850df3ecaae4bcd5e9c5b20d2a73dfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.25.0.aar",
          "url": "core-ui-0.25.0.aar",
          "size": 164754,
          "sha512": "262f5545e954510d55b645a53eeb980d8d4dc5ca8b60833a800301f2fe725fadc8192b19d0383c7a0d33b7f58bb2b923faacb341f0299280535e33fc93d6ddc5",
          "sha256": "63b5a4251fa3cce5310cb6e2cff4a91e3b99e3c8d3dce0160db940fb3e43d185",
          "sha1": "4b1467cd56fef3e0ef161c9407790c4e71a51248",
          "md5": "5850df3ecaae4bcd5e9c5b20d2a73dfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ui-0.25.0-sources.jar",
          "url": "core-ui-0.25.0-sources.jar",
          "size": 32446,
          "sha512": "35a8d58a8296c26c4440bff258e3666f94eb7926abedfd1d09da04e85205cbca670e15834667d96cb432fb241a5eb22863bd161a6cf789ffaf7469c55eff5342",
          "sha256": "4626e7e06ff72784efd6825bc27e4c7d8469aea6a0b971cd2dc63be32f9b7fe8",
          "sha1": "c197f25658e786ea609c622dbdbe27489ab18d13",
          "md5": "fc7f2903622f231f09a648c1829eb1aa"
        }
      ]
    }
  ]
}
