{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-database",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "database-metadata-0.23.0.jar",
          "url": "core-database-0.23.0.jar",
          "size": 3322,
          "sha512": "4be6671db1a1d41b7f815f0dba04c50d93698c5d5120c62b5fbbfee6b6fffe0b090c381edd31090f882b960aae857a98750654caef1bbffc8cc52215dbf174f5",
          "sha256": "c0408b9192903bfc67070fc9d70a8d30350e215b03d1b1fa15fb192af995e4d9",
          "sha1": "d045cff5ce6480736c10681c5ae90da4fb0c0f74",
          "md5": "c1184df9099e227930a9b90d4df74528"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "database-kotlin-0.23.0-sources.jar",
          "url": "core-database-0.23.0-sources.jar",
          "size": 2104,
          "sha512": "4490c10c602579a4558dadd16286df60598548bfc3080e3219a526e37db130140a319a4dda017d6124ec7f22799ce71059571723fc8fb30790f94f1f874e9f7d",
          "sha256": "aba816c8af3c5cd99718856e62b068ba054b269470163cda1b650ff6528fa9b3",
          "sha1": "d73da313d43e8ad8ab616ebec2906b0312caf837",
          "md5": "fcf5ff75f6c30576b4acf9df13f1e998"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-database-android/0.23.0/core-database-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-database-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-database-android/0.23.0/core-database-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-database-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-database-android/0.23.0/core-database-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-database-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iosarm64/0.23.0/database-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iosarm64/0.23.0/database-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iosarm64/0.23.0/database-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iossimulatorarm64/0.23.0/database-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iossimulatorarm64/0.23.0/database-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iossimulatorarm64/0.23.0/database-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iosx64/0.23.0/database-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iosx64/0.23.0/database-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../database-iosx64/0.23.0/database-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "database-iosx64",
        "version": "0.23.0"
      }
    }
  ]
}
