{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-di-koin",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.16.0.aar",
          "url": "core-di-koin-0.16.0.aar",
          "size": 18669,
          "sha512": "3cea4d4f7705bff6f491904a808aed62d2634a2c4869af114b39e9ddb3af409bfbeed852b508616a8f63626d3ad8ca013fd0c682e96ee0a8c4ab55917b0ba8a3",
          "sha256": "13fce334fec861c12d79d0b9106723d663b39be5c82fcf3b61d6a9e15828c88f",
          "sha1": "32e7ecb5bf70bba1daf32242af6921b8f86184be",
          "md5": "c2e59d355e2fdeb6ae6b8b2b663aeb12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.16.0.aar",
          "url": "core-di-koin-0.16.0.aar",
          "size": 18669,
          "sha512": "3cea4d4f7705bff6f491904a808aed62d2634a2c4869af114b39e9ddb3af409bfbeed852b508616a8f63626d3ad8ca013fd0c682e96ee0a8c4ab55917b0ba8a3",
          "sha256": "13fce334fec861c12d79d0b9106723d663b39be5c82fcf3b61d6a9e15828c88f",
          "sha1": "32e7ecb5bf70bba1daf32242af6921b8f86184be",
          "md5": "c2e59d355e2fdeb6ae6b8b2b663aeb12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-di-koin-0.16.0-sources.jar",
          "url": "core-di-koin-0.16.0-sources.jar",
          "size": 4411,
          "sha512": "1f44a4b5b2452219b846eae2375b5dde93e56241dc794896107e12e699d509494e3244638211d555350b271474d0182dc20f7061e624aec5b5f780beb44fd724",
          "sha256": "b3df387f5280c9f21a2ac7bbd85daa5f9fb75b3c5df9a8a4b5a77b2c7ba8644d",
          "sha1": "7284de048800696efd699fe3b7c297d27b08433d",
          "md5": "6cf8797d945c434e659bbf65957e7909"
        }
      ]
    }
  ]
}
