{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig-posthog/0.24.1/core-remoteconfig-posthog-0.24.1.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-posthog",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-iosArm64Main-0.24.1.klib",
          "url": "core-remoteconfig-posthog-iosarm64-0.24.1.klib",
          "size": 16438,
          "sha512": "0111b06bb2de623939d2b94c5f53d37dd8a3a6d0b35672fb663a3e988ea0213661e5392a8348d629a20bc48b919145ef2864b3bb4a006e73a42472ec979c49b8",
          "sha256": "00035cfa6c6fa28a4b8c99f385c052bfbab1e2861e432a51171c1fa12dc6ba05",
          "sha1": "2412f1405f9b2dd86f2e6d7f60e4b7e22efe9273",
          "md5": "8df935b9247728e7122a8e1b69b34f4c"
        },
        {
          "name": "core-remoteconfig-posthog-iosArm64Cinterop-PostHogMain-0.24.1.klib",
          "url": "core-remoteconfig-posthog-iosarm64-0.24.1-cinterop-PostHog.klib",
          "size": 20584,
          "sha512": "5d786a7d2a0ac3e2c4aa1848847b4c2468f6df8d9a33025ca249436ed35ed3a750f6f9aa389479ebbe9bbe7e57ee2d261bc3cc1c56965bf0cd39b86df18de44a",
          "sha256": "d317a6022adab019f356726977f4199696383307c73271b427f99769a74991e6",
          "sha1": "6df5fc96cad3db54e40e7b84ee373430f4e20efd",
          "md5": "72e10bd61f3410d5e97616c0c98c2346"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-posthog-iosarm64-0.24.1-sources.jar",
          "url": "core-remoteconfig-posthog-iosarm64-0.24.1-sources.jar",
          "size": 5224,
          "sha512": "f011cc9ab80c3f5c23a15f78d071a90d573211ce6769fb2bcfb256a3f9f17d043ed5bf78bf3aa5eb1a2bcb62a0878cc238ff50b9aa0f3a39e1b3747d137746c0",
          "sha256": "509e63a4bceee9a217759e53e2f26326772dcdae702e701641f3c99dec7367f2",
          "sha1": "0869348d3acad764d6bae1b814141aa77a39921d",
          "md5": "00128daf39b5d3af1a3c976e6fc79a15"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-iosarm64-0.24.1-metadata.jar",
          "url": "core-remoteconfig-posthog-iosarm64-0.24.1-metadata.jar",
          "size": 56266,
          "sha512": "af5f6f7009f16c5fd9de8aaef06ba727c90c779e2d25fe14ec7e223c31fffc3d5b38923aab7ad30c6ef1653bd20ae1fd5130f28d56d9e00a7d29de61ea1244a2",
          "sha256": "1b72f59c41cb4cf45e8f0a9430534eb317064aa0108c51c14f55ff5c30cec14a",
          "sha1": "165fea67c5eaad1d4aa7fdb5a8f873793f359878",
          "md5": "22b1b798085c359e8b392fd8915eb8d3"
        }
      ]
    }
  ]
}
