{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.21.0.jar",
          "url": "core-ksp-processor-0.21.0.jar",
          "size": 33243,
          "sha512": "11660d28d6f5780fc4ae8f2841c09c1c14b39ec08c6b46321b7464304383093b63589e5b2685dce198503019da68005df0f4166d18263cdf6107a2c3b14aef3a",
          "sha256": "c7800b8abf73ee34b76a005890f1eb8e87c4c31fc140c638bdb45efc748b6197",
          "sha1": "deb105c3ae547d7b55e6ff35580ea538b293e11b",
          "md5": "7718c3fc1e30d5a51e330af45de460c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.21.0.jar",
          "url": "core-ksp-processor-0.21.0.jar",
          "size": 33243,
          "sha512": "11660d28d6f5780fc4ae8f2841c09c1c14b39ec08c6b46321b7464304383093b63589e5b2685dce198503019da68005df0f4166d18263cdf6107a2c3b14aef3a",
          "sha256": "c7800b8abf73ee34b76a005890f1eb8e87c4c31fc140c638bdb45efc748b6197",
          "sha1": "deb105c3ae547d7b55e6ff35580ea538b293e11b",
          "md5": "7718c3fc1e30d5a51e330af45de460c5"
        }
      ]
    }
  ]
}
