{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.24.2/core-remoteconfig-0.24.2.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosSimulatorArm64Main-0.24.2.klib",
          "url": "core-remoteconfig-iossimulatorarm64-0.24.2.klib",
          "size": 17014,
          "sha512": "20fa1b21a77256b2694b844a3e52bae493c23197a8edb073fe770c123ac445f6676f7b404511c27d9601b2d10657365afa6f37afdd815788795e6739b588ca37",
          "sha256": "1299c54260c1ebe9278bfabc5079376a05cede4ace7eb0512cbe7a9b607b6396",
          "sha1": "f34a4444928251ccce2fa80a1ca6be432b5d0c2b",
          "md5": "603bc0a691bd2e9274a23e1e9255d95e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-iossimulatorarm64-0.24.2-sources.jar",
          "url": "core-remoteconfig-iossimulatorarm64-0.24.2-sources.jar",
          "size": 5911,
          "sha512": "80324a440ee63060b4ec2b7238516b6e191d40d41e5719093e2731b9b124ca1c0500be21264301227c132f7c840e291b6bcfcbe990e20d0230fb37fd91cec712",
          "sha256": "31c6b3dd523d0dfa8013d82c7080448dcb4621ebcbf25394f00ab957cf18863e",
          "sha1": "58b7aaf98ebce30a132bd2e82f05902727e98b86",
          "md5": "73fa0791cfbd433abc542059e2a5593b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iossimulatorarm64-0.24.2-metadata.jar",
          "url": "core-remoteconfig-iossimulatorarm64-0.24.2-metadata.jar",
          "size": 261,
          "sha512": "36ff79c9a117f3bb67975f8a5aeb7ae58d5b618e1a7549568bc52b3b229bad66b2181ba0fc6f47a899309f487bf00f31f9c7d2745a60f85207d31119d6dcb27a",
          "sha256": "429d611035fc1b558589d8fb22770d8f39bcbc5213c8a091c8c60be95a540cbd",
          "sha1": "24b6bf20b240936c6da6a9702d5778da35a4fa52",
          "md5": "85d207e461cc5ce90429de5ca3e23347"
        }
      ]
    }
  ]
}
