{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-annotation/0.23.0/core-annotation-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-annotation",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-iosX64Main-0.23.0.klib",
          "url": "annotation-iosx64-0.23.0.klib",
          "size": 8970,
          "sha512": "132e81b2310c273a384432b740709a0ca2f143fe9e20d412dadd2bb2c1e563546e52b939e20900e11eaf84b968d8805ea02d049b494054a1150cbfba9203129f",
          "sha256": "b200a51526878a2e8aa9abf6903b8e352c7f7995e7e890bb9386c3afa9e6cc89",
          "sha1": "b14547d814a1e8e67bbd6e6c289ec296824b12ef",
          "md5": "18267eb4260df7f0af13bff66beeb933"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-iosx64-0.23.0-sources.jar",
          "url": "annotation-iosx64-0.23.0-sources.jar",
          "size": 3421,
          "sha512": "d4a0fe87a08492aa7782b988891720240ff4d95d497e7b952b72cc3400e043a08ed60ffd32e3b841a6a83d9658bec7676a58cc97355ab5df2f0c913b1f61ecae",
          "sha256": "a5a6f44fed26ca24da7e18e0e932831b979dd21bc60de115ee520340cb64ba63",
          "sha1": "a5cee5928dd72956a7b6c60f21145e3c05e84cec",
          "md5": "14ab7d440ff6f9aa670c6aab091ed4ff"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-iosx64-0.23.0-metadata.jar",
          "url": "annotation-iosx64-0.23.0-metadata.jar",
          "size": 261,
          "sha512": "f2002f4822e5405034fc9fb40efd778338d20f0528c6f616ca99b2880d13e098a74ae3c7e0c2081129136c058801252ff97019f5bd921fc80402aa1ffbb13bba",
          "sha256": "86f67559fcd3f95f2478481f8fe4dab2f22c1fe936b6082a4bdb3531707ac0a9",
          "sha1": "8d4ccb42e100066724992b19bc5aa1de044d107d",
          "md5": "4426512042e0e2373adae434ea16aa43"
        }
      ]
    }
  ]
}
