{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.24.1/core-remoteconfig-0.24.1.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosArm64Main-0.24.1.klib",
          "url": "core-remoteconfig-iosarm64-0.24.1.klib",
          "size": 16948,
          "sha512": "faee1fb5e1f2584b825aa13af20801db200e6ff9b01999bb3a7a06d64a20971eb194a2c7d5ba40f69bb2931b66b9710d48c251fff7ad845ae042fb9448e365c2",
          "sha256": "76ee0fe7796ddbdd6ef73ad4f0c5ea9144897756e7fb26459cc53eee14f21ce5",
          "sha1": "dcee656203d4e15a78a723068a13ae578c6b7bd2",
          "md5": "bd2099e78042b6e7ea835d93932e5414"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.24.1-sources.jar",
          "url": "core-remoteconfig-iosarm64-0.24.1-sources.jar",
          "size": 5911,
          "sha512": "80324a440ee63060b4ec2b7238516b6e191d40d41e5719093e2731b9b124ca1c0500be21264301227c132f7c840e291b6bcfcbe990e20d0230fb37fd91cec712",
          "sha256": "31c6b3dd523d0dfa8013d82c7080448dcb4621ebcbf25394f00ab957cf18863e",
          "sha1": "58b7aaf98ebce30a132bd2e82f05902727e98b86",
          "md5": "73fa0791cfbd433abc542059e2a5593b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.24.1-metadata.jar",
          "url": "core-remoteconfig-iosarm64-0.24.1-metadata.jar",
          "size": 261,
          "sha512": "0e9f1d6c0e38027cfb0d7d2a8b82a132e5b170a3440db807d1cd47b121b37c253ec733face31686ccb84b16b0dc8fd6d4a01c7358d09fd088807715b100df4bd",
          "sha256": "687c2df2b8ea0d7bf8d2caac7c8574a6841e6aa1057309fb8946e74236519cfa",
          "sha1": "5013e60a0ca5c3a0b0dcd0e1533bca6f86ac70b3",
          "md5": "6a09de9e95090b1448261bf01e341c7f"
        }
      ]
    }
  ]
}
