{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.13.0.jar",
          "url": "core-ksp-processor-0.13.0.jar",
          "size": 33243,
          "sha512": "e5066b0b64ea612a45bcd0f4f3b638df86bba6538a8709a5d2d679787b13b16069854a3f413976f407a19214d8090bebfef37d907fa5c2fca4d89b675e218856",
          "sha256": "31e3ee18915cf278fc719398bd99aa1166adf59e1c2284a2b1c6bdffe2ba6f20",
          "sha1": "009c8ae87ca0f315f30d780ea758094d27a93c0b",
          "md5": "7dcf5931810134408b985b4e70a2d92b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.13.0.jar",
          "url": "core-ksp-processor-0.13.0.jar",
          "size": 33243,
          "sha512": "e5066b0b64ea612a45bcd0f4f3b638df86bba6538a8709a5d2d679787b13b16069854a3f413976f407a19214d8090bebfef37d907fa5c2fca4d89b675e218856",
          "sha256": "31e3ee18915cf278fc719398bd99aa1166adf59e1c2284a2b1c6bdffe2ba6f20",
          "sha1": "009c8ae87ca0f315f30d780ea758094d27a93c0b",
          "md5": "7dcf5931810134408b985b4e70a2d92b"
        }
      ]
    }
  ]
}
