{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.27.0/core-remoteconfig-0.27.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosArm64Main-0.27.0.klib",
          "url": "core-remoteconfig-iosarm64-0.27.0.klib",
          "size": 17323,
          "sha512": "dc4a9b1c1d2c27e899b66e184b6062fab1e86d9358e427b0b24e5dd3ff06d38b621e73280ed16dbf89a664beb81035291b2a0d4bd3c61f7985882e961329f654",
          "sha256": "4fd3b45f1465c1047b0691520e304d1cdc83e067215933774625504f17c72521",
          "sha1": "b4c238697f394d2d1fd6a8ebef004c2485523bc4",
          "md5": "f6b095eaffe5381eb456b42db5924d89"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.27.0-sources.jar",
          "url": "core-remoteconfig-iosarm64-0.27.0-sources.jar",
          "size": 6158,
          "sha512": "5cc7a431be51a3ca4890d5426fa79db8156f7ca702e6a96729caf106048d29c88ac2a565fbb77e3ab12e30352d961a1e5919770ab027709254c03795a0999b8b",
          "sha256": "6b5d4855123e2c062240211f5ce45a94c1894066ffbcab6ce6297aa38da87796",
          "sha1": "323cea1e0eb45d376631b852c5d04be2c2b6eb43",
          "md5": "9f2b710637a33ddbd8445c996cb19ee3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.27.0-metadata.jar",
          "url": "core-remoteconfig-iosarm64-0.27.0-metadata.jar",
          "size": 261,
          "sha512": "fe03a6b958278564fae12cbd095257cce775207448f6063ceba846f736286b5eba202346a421077700787eae4e47515e291337214ff3dc07b956ef19eef51e0f",
          "sha256": "34166f0194f8ef88485e60c86912cf678f83d4fea63da05f15663681b5ae414a",
          "sha1": "737e5097f8e30baf370ac17ace69a350ec4b03ae",
          "md5": "bf6fc08084137b6b0234f6451b7a7c11"
        }
      ]
    }
  ]
}
