{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.6.0.jar",
          "url": "core-ksp-processor-0.6.0.jar",
          "size": 33242,
          "sha512": "9be9c3d10257baa5cc8fe70b4b38d09ea5acc955d348f17ce0743515944ce152955468cc90322322f6344703fa59d84162a7646c796cc51123a3bffdfaebec7c",
          "sha256": "18e215bb92d3bff5f612c8885de54de72557e68a5d02af1154e575806313a13e",
          "sha1": "ddf05803fe6733bb58af239c17dbb40a81a4c10b",
          "md5": "6ce4053f888a156a928a2f1849195ec7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.6.0.jar",
          "url": "core-ksp-processor-0.6.0.jar",
          "size": 33242,
          "sha512": "9be9c3d10257baa5cc8fe70b4b38d09ea5acc955d348f17ce0743515944ce152955468cc90322322f6344703fa59d84162a7646c796cc51123a3bffdfaebec7c",
          "sha256": "18e215bb92d3bff5f612c8885de54de72557e68a5d02af1154e575806313a13e",
          "sha1": "ddf05803fe6733bb58af239c17dbb40a81a4c10b",
          "md5": "6ce4053f888a156a928a2f1849195ec7"
        }
      ]
    }
  ]
}
