{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.17.0.jar",
          "url": "core-ksp-processor-0.17.0.jar",
          "size": 33243,
          "sha512": "670c7bd9738e861242cbfdded82bc51666a125c2b1b935ec679a39610c1bf4b4624456d8cc389c23a406bace76a5de788ae14072abc228bba83adb7b679d3e70",
          "sha256": "a98a7ebc4e03bc6b472933690c4717a864464fe046a0f09df17cec363fd7b013",
          "sha1": "57a7eca8b14ba9574c35f7576f791245f8c08512",
          "md5": "8dfb51e5474542b6ed71701c54e735f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.17.0.jar",
          "url": "core-ksp-processor-0.17.0.jar",
          "size": 33243,
          "sha512": "670c7bd9738e861242cbfdded82bc51666a125c2b1b935ec679a39610c1bf4b4624456d8cc389c23a406bace76a5de788ae14072abc228bba83adb7b679d3e70",
          "sha256": "a98a7ebc4e03bc6b472933690c4717a864464fe046a0f09df17cec363fd7b013",
          "sha1": "57a7eca8b14ba9574c35f7576f791245f8c08512",
          "md5": "8dfb51e5474542b6ed71701c54e735f0"
        }
      ]
    }
  ]
}
