{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-logger-firebase",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-firebase-metadata-0.23.0.jar",
          "url": "core-logger-firebase-0.23.0.jar",
          "size": 3093,
          "sha512": "a03864dd47833a098d65efce05fbff6e8be42954700dcb5196744e6890ee0158196db2f9fa951a2e8bcbad2abec07c69844210403f71529e4bc379376d087021",
          "sha256": "57ac29434ae049ff63d0203d115274c15d3f373a96bb72a740aff16f727bc567",
          "sha1": "39d75a6705865c7423aa9b442b1b9377da4cef09",
          "md5": "81d519f629d78efff99d5a47ce162970"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "logger-firebase-kotlin-0.23.0-sources.jar",
          "url": "core-logger-firebase-0.23.0-sources.jar",
          "size": 4059,
          "sha512": "60bb8a8e25516b13054efb75ffff3dcb27e28f0239a02aa5aabb902789c1dc549d2ce793a8dd897e3d0c618e1d321df08bb72658225e0754f90cee458182ddca",
          "sha256": "b30f72b29aca837e7f16b4514d088c9ead41ba127792c25e2b6d52b5a2b95dcc",
          "sha1": "15b495d46c3b0409bc93179f4ab7da143746e392",
          "md5": "b33b2c3eec9fab0424ff58553b6fcec8"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-firebase-android/0.23.0/core-logger-firebase-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-firebase-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-firebase-android/0.23.0/core-logger-firebase-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-firebase-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-firebase-android/0.23.0/core-logger-firebase-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-firebase-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iosarm64/0.23.0/logger-firebase-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iosarm64/0.23.0/logger-firebase-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iosarm64/0.23.0/logger-firebase-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iossimulatorarm64/0.23.0/logger-firebase-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iossimulatorarm64/0.23.0/logger-firebase-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iossimulatorarm64/0.23.0/logger-firebase-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iosx64/0.23.0/logger-firebase-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iosx64/0.23.0/logger-firebase-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../logger-firebase-iosx64/0.23.0/logger-firebase-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "logger-firebase-iosx64",
        "version": "0.23.0"
      }
    }
  ]
}
