{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-logger-firebase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-firebase-0.8.0.aar",
          "url": "core-logger-firebase-0.8.0.aar",
          "size": 6370,
          "sha512": "d728f8d29cfb19f46f8add26428df3970458c7884d3aa9f84969256ab140b4aab699b62a38df19a6ba29ab99b75e623b37b2686ee0c7471478ed059e475a9f64",
          "sha256": "3d42d9792b663b92642eee097f4a3f04c3886a7b57c061868529c39a94e8956d",
          "sha1": "c668f61bbdfacf864ef6e7cadbc097c0716eb360",
          "md5": "800d65771ab0682b286ada7ea5bb5cbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-firebase-0.8.0.aar",
          "url": "core-logger-firebase-0.8.0.aar",
          "size": 6370,
          "sha512": "d728f8d29cfb19f46f8add26428df3970458c7884d3aa9f84969256ab140b4aab699b62a38df19a6ba29ab99b75e623b37b2686ee0c7471478ed059e475a9f64",
          "sha256": "3d42d9792b663b92642eee097f4a3f04c3886a7b57c061868529c39a94e8956d",
          "sha1": "c668f61bbdfacf864ef6e7cadbc097c0716eb360",
          "md5": "800d65771ab0682b286ada7ea5bb5cbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-logger-firebase-0.8.0-sources.jar",
          "url": "core-logger-firebase-0.8.0-sources.jar",
          "size": 1889,
          "sha512": "31dc5f26692dc301589e32a24901ef42686a5959839b4ee41363c2dee66909b1b59b2e53c7f37e33a7c825bf44337cd3520ee1c1a4ce9ff5e9c16c0ab99e5f6e",
          "sha256": "6980c4ee0dc93aa393b02572e6837135c01d8fdb597e62030b4a48b22e7bbe22",
          "sha1": "26e3473f76a38b59e5fd82f0c7fb1070d7bad91e",
          "md5": "2c7f16c4ee55f6ae6484361b0e5b6809"
        }
      ]
    }
  ]
}
