{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger-firebase/0.23.0/core-logger-firebase-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger-firebase",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-firebase-release.aar",
          "url": "core-logger-firebase-android-0.23.0.aar",
          "size": 7624,
          "sha512": "9bcef3b3ff27894b6bd4c6a7ac5228a73826609e0f53cdbf1a9359962e22d5f07262414ed28a68b3e6283aa2cc3fb5d463733053abc3c9f8da7fde91776def03",
          "sha256": "8794335983b0c4b6c657a48a4fbdfe9dece43848dbb6ec2d93dcebe492e861c2",
          "sha1": "f51f8911839bb1d3d30eda3981f17aa75e297cdc",
          "md5": "4be0f535c7913cae5344638bf80200a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "logger-firebase-release.aar",
          "url": "core-logger-firebase-android-0.23.0.aar",
          "size": 7624,
          "sha512": "9bcef3b3ff27894b6bd4c6a7ac5228a73826609e0f53cdbf1a9359962e22d5f07262414ed28a68b3e6283aa2cc3fb5d463733053abc3c9f8da7fde91776def03",
          "sha256": "8794335983b0c4b6c657a48a4fbdfe9dece43848dbb6ec2d93dcebe492e861c2",
          "sha1": "f51f8911839bb1d3d30eda3981f17aa75e297cdc",
          "md5": "4be0f535c7913cae5344638bf80200a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logger-firebase-android-0.23.0-sources.jar",
          "url": "core-logger-firebase-android-0.23.0-sources.jar",
          "size": 4034,
          "sha512": "70509198c4725ee8b4f139df85e97215ccd3d6265da68cc41b775c003ac3df53e3b630465df4d26c04d0c3e0f8bc5d300fe4ed510630283089ddf5866bb8856e",
          "sha256": "bdcf069dbd3bad8a7333e8c32c760d8396c7791f3764610e8855f873e7e65db9",
          "sha1": "94ae716ad3fc5041f83d3e3f2c0b7d2f63094473",
          "md5": "6afcdc6470ff9111cd6544b6e494a49f"
        }
      ]
    }
  ]
}
