{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ui",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.22.0.aar",
          "url": "core-ui-0.22.0.aar",
          "size": 164085,
          "sha512": "10e45c1bb46169f140b17a6edf4a0e09d405c6b6b2b893213f24cbbca3aa8a822b33c72439e17c5eb178d45a1906ba57127d0e1df52c34b8483944bb6e7b02cd",
          "sha256": "824b3da2078e35e6a0d3967aeb1c7afa68a346d73e9271cb8326966abda2d834",
          "sha1": "0098eabb443f10a68b8a3e3c64c67e22d0bc525f",
          "md5": "83267b998e4de1ad41f94390112a64f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.22.0.aar",
          "url": "core-ui-0.22.0.aar",
          "size": 164085,
          "sha512": "10e45c1bb46169f140b17a6edf4a0e09d405c6b6b2b893213f24cbbca3aa8a822b33c72439e17c5eb178d45a1906ba57127d0e1df52c34b8483944bb6e7b02cd",
          "sha256": "824b3da2078e35e6a0d3967aeb1c7afa68a346d73e9271cb8326966abda2d834",
          "sha1": "0098eabb443f10a68b8a3e3c64c67e22d0bc525f",
          "md5": "83267b998e4de1ad41f94390112a64f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ui-0.22.0-sources.jar",
          "url": "core-ui-0.22.0-sources.jar",
          "size": 32446,
          "sha512": "35a8d58a8296c26c4440bff258e3666f94eb7926abedfd1d09da04e85205cbca670e15834667d96cb432fb241a5eb22863bd161a6cf789ffaf7469c55eff5342",
          "sha256": "4626e7e06ff72784efd6825bc27e4c7d8469aea6a0b971cd2dc63be32f9b7fe8",
          "sha1": "c197f25658e786ea609c622dbdbe27489ab18d13",
          "md5": "fc7f2903622f231f09a648c1829eb1aa"
        }
      ]
    }
  ]
}
