{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-logger",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-0.9.0.aar",
          "url": "core-logger-0.9.0.aar",
          "size": 55117,
          "sha512": "4521d902796f3749cef63460951b5d0894fbd8e18afdceb6e2aa840835425a29d336848841269c8b49e56d3409f92b5a5e8e03a4669b92c2eafaf703f5ad4516",
          "sha256": "2912889001fa5976dd1d563b13aeb6c25fe6106b9bc05ad454092644420fed45",
          "sha1": "88d33d2fa64068519d22d8c340a6c904eb5a50f2",
          "md5": "909aa3c037bf53f70b9927ef56076ce9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-0.9.0.aar",
          "url": "core-logger-0.9.0.aar",
          "size": 55117,
          "sha512": "4521d902796f3749cef63460951b5d0894fbd8e18afdceb6e2aa840835425a29d336848841269c8b49e56d3409f92b5a5e8e03a4669b92c2eafaf703f5ad4516",
          "sha256": "2912889001fa5976dd1d563b13aeb6c25fe6106b9bc05ad454092644420fed45",
          "sha1": "88d33d2fa64068519d22d8c340a6c904eb5a50f2",
          "md5": "909aa3c037bf53f70b9927ef56076ce9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-logger-0.9.0-sources.jar",
          "url": "core-logger-0.9.0-sources.jar",
          "size": 18913,
          "sha512": "239f69b1752b27d10476ef9ee34770605de224049d0cece7f096a36cf3936cc966a937c3e35bebaa7fd4df33d5e9d5165f637aafbe200f5a105dc27356d2be0e",
          "sha256": "18855d04aea2c0d4ad1c9b091d52903d67218969f9e084716dbe163f3e4f90da",
          "sha1": "09ca4f577829780f89bef10a0a401c14bc7ce7da",
          "md5": "844cbaef979f635b0394220fc4dc3c97"
        }
      ]
    }
  ]
}
