{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.25.0/core-remoteconfig-0.25.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosArm64Main-0.25.0.klib",
          "url": "core-remoteconfig-iosarm64-0.25.0.klib",
          "size": 16948,
          "sha512": "faee1fb5e1f2584b825aa13af20801db200e6ff9b01999bb3a7a06d64a20971eb194a2c7d5ba40f69bb2931b66b9710d48c251fff7ad845ae042fb9448e365c2",
          "sha256": "76ee0fe7796ddbdd6ef73ad4f0c5ea9144897756e7fb26459cc53eee14f21ce5",
          "sha1": "dcee656203d4e15a78a723068a13ae578c6b7bd2",
          "md5": "bd2099e78042b6e7ea835d93932e5414"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.25.0-sources.jar",
          "url": "core-remoteconfig-iosarm64-0.25.0-sources.jar",
          "size": 5911,
          "sha512": "80324a440ee63060b4ec2b7238516b6e191d40d41e5719093e2731b9b124ca1c0500be21264301227c132f7c840e291b6bcfcbe990e20d0230fb37fd91cec712",
          "sha256": "31c6b3dd523d0dfa8013d82c7080448dcb4621ebcbf25394f00ab957cf18863e",
          "sha1": "58b7aaf98ebce30a132bd2e82f05902727e98b86",
          "md5": "73fa0791cfbd433abc542059e2a5593b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.25.0-metadata.jar",
          "url": "core-remoteconfig-iosarm64-0.25.0-metadata.jar",
          "size": 261,
          "sha512": "e379ec859b1d6c6ee99a043bf55b2ca254ef5ed7f7d1756be64ff99c3a5a481a3f1155778b8515db561acfee3b2db937b8a571459d1c5cc30225679c326b4c2d",
          "sha256": "996928757cc95c8aa29c568301d5896bdba1ff8d4f296b2cafadb0d00cf70a69",
          "sha1": "a318703ad1b8839fb34d7e5653036a1f16e23e2e",
          "md5": "5d5527c2cf9ab2bd91b31623abbb3314"
        }
      ]
    }
  ]
}
