{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-database/0.25.0/core-database-0.25.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-database",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-database-release.aar",
          "url": "core-database-android-0.25.0.aar",
          "size": 5347,
          "sha512": "379d42c9b40ab38ee9cdcec801bf99685fe51a34e2161bc8963618a4d9dd947be4590bd0589c22a5008e0e91271fa51c11af0e4ddf3a29542bf3343aca41f0ba",
          "sha256": "79778c476cc5bd607dcda6b096c32d776e804e9c0a05a560e6e3b9534cc45a87",
          "sha1": "b6fe06d84f688d419008d73afa2f588aaf756422",
          "md5": "bf076fcaceb65c2ef7ca118c7dcb1c71"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.25.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-database-release.aar",
          "url": "core-database-android-0.25.0.aar",
          "size": 5347,
          "sha512": "379d42c9b40ab38ee9cdcec801bf99685fe51a34e2161bc8963618a4d9dd947be4590bd0589c22a5008e0e91271fa51c11af0e4ddf3a29542bf3343aca41f0ba",
          "sha256": "79778c476cc5bd607dcda6b096c32d776e804e9c0a05a560e6e3b9534cc45a87",
          "sha1": "b6fe06d84f688d419008d73afa2f588aaf756422",
          "md5": "bf076fcaceb65c2ef7ca118c7dcb1c71"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-database-android-0.25.0-sources.jar",
          "url": "core-database-android-0.25.0-sources.jar",
          "size": 2104,
          "sha512": "4490c10c602579a4558dadd16286df60598548bfc3080e3219a526e37db130140a319a4dda017d6124ec7f22799ce71059571723fc8fb30790f94f1f874e9f7d",
          "sha256": "aba816c8af3c5cd99718856e62b068ba054b269470163cda1b650ff6528fa9b3",
          "sha1": "d73da313d43e8ad8ab616ebec2906b0312caf837",
          "md5": "fcf5ff75f6c30576b4acf9df13f1e998"
        }
      ]
    }
  ]
}
