{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger/0.25.0/core-logger-0.25.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-iosArm64Main-0.25.0.klib",
          "url": "core-logger-iosarm64-0.25.0.klib",
          "size": 63131,
          "sha512": "5489e546f8d96de7fb8624e532b91ce45973dd3bdfa2885836550319a1ff5b6034b8cbbf2f72ac68f5165b5f5ad0b8e8ef797dfde540a73b1d294c3d6377a0b3",
          "sha256": "2d499403aa4311146cbed311983d4edf878f2e7d2e98af05566454803ad55bb9",
          "sha1": "bccd450e3dbb3c7db55d2eb2e7503102fc49779b",
          "md5": "2a193b355ce653e621f08a63aca06314"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-logger-iosarm64-0.25.0-sources.jar",
          "url": "core-logger-iosarm64-0.25.0-sources.jar",
          "size": 23929,
          "sha512": "063dd56f60de910c07137f78ea6f157e3ee8477b7d76bc8b760ced901ad3a8361f9bc8966de424abcdb0d14012e5954171423a4f2f264f2042acee7b14b77869",
          "sha256": "6c8953055122a44d7eab85cdcd9d8f7c5c0d8809a05b3f45409624880819ea44",
          "sha1": "6bcf5e625931b3a117ba7ac205709a182b8013eb",
          "md5": "c457ec00f07b10a0da189f10e77a348b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-iosarm64-0.25.0-metadata.jar",
          "url": "core-logger-iosarm64-0.25.0-metadata.jar",
          "size": 4222,
          "sha512": "107736619c4da66525b2229fbb3940f1d8b59f6bd6ff43d3700448fecfdf9deb3a05939db9759cc18493e0d5a3d9854e59dbc560d0ff7343a525fc9113d94413",
          "sha256": "2b8e75527ce1962d7a3e90b4d8f5a2f2a06737bd581fd11ae976d525f6d4e3a7",
          "sha1": "c645469be5ddf59064ddeba5806766cf95a62112",
          "md5": "4023f95b97bffb444c6be98c5de010dc"
        }
      ]
    }
  ]
}
