{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig-firebase/0.27.0/core-remoteconfig-firebase-0.27.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-firebase",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-firebase-iosSimulatorArm64Main-0.27.0.klib",
          "url": "core-remoteconfig-firebase-iossimulatorarm64-0.27.0.klib",
          "size": 18390,
          "sha512": "7a89fe10212534cf54fd21d79d41ca8b7bb0a4d071f7f5886c8e791ad88eadf09f76ac6ad1459aec36c78b19cd13812cae1555245bf0989f25e457268d44b8fd",
          "sha256": "5ffe5ffff003bbf75b9fc8d82b1c336e82ea16dcd9d6e7064f10569bad649669",
          "sha1": "c0442aac9e74ad6c5172f163fb94fde906dd4779",
          "md5": "95d8305bb7649d6422107729723ab280"
        },
        {
          "name": "core-remoteconfig-firebase-iosSimulatorArm64Cinterop-FirebaseRemoteConfigMain-0.27.0.klib",
          "url": "core-remoteconfig-firebase-iossimulatorarm64-0.27.0-cinterop-FirebaseRemoteConfig.klib",
          "size": 12484,
          "sha512": "2998e6a74a1de408da17d57337dc102f4d820df97a45e75dbd056e377c5a39286cc88ce264f42a693f66f89cfffdaabd0367633194a8bd5efdfc18f11a070a51",
          "sha256": "88b7163d4eb9ea9aa8ddd16d3d34bccadec54e5e011f714a1aecc846279536b5",
          "sha1": "4fdc2f001a9ac0adf7114269b6ac759093ec452b",
          "md5": "6633ab7efce6066cc0faf1f17e11f928"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-firebase-iossimulatorarm64-0.27.0-sources.jar",
          "url": "core-remoteconfig-firebase-iossimulatorarm64-0.27.0-sources.jar",
          "size": 5635,
          "sha512": "20ad216fbf8d320f40eaac4773d3c33f098b3331fbb15f29eae65de8cf3e13cb772e4365f6a343dcc05f607e6b2864ef137044aa2df0eaaf5bfd3404fbfb645f",
          "sha256": "1040c379867a5ed32cef5989d3a0c33ade2e60988fa25ed5fe02272c1e7c938a",
          "sha1": "2202c4ce8981f8dfa5fd8bc48f7a17d8a0c2dc05",
          "md5": "fd855335c96172f3864731e3c147fd7b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-firebase-iossimulatorarm64-0.27.0-metadata.jar",
          "url": "core-remoteconfig-firebase-iossimulatorarm64-0.27.0-metadata.jar",
          "size": 29620,
          "sha512": "3e1f9ef0554d92f91645ca35ba8d15cf1ef95c20aa46f81fe2f31c410e8d14de82241120c9de8dfc70f18437aadfac84e0d9d9435fd27e9e10b5dadcfc462aa0",
          "sha256": "1088e44c3255a9ff814f4a46972cee7b04d19afe08018b9598197b58354e1896",
          "sha1": "52b04bc9269dfd9a460a7959efe3d63c5ed2fca3",
          "md5": "59df2968de7a96d40f4414ed70b0f78c"
        }
      ]
    }
  ]
}
