{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.16.0.jar",
          "url": "core-ksp-processor-0.16.0.jar",
          "size": 33243,
          "sha512": "58c274b911f1b2ed1bdaee94e2475b1a300c29cd0e1a19cb2346b969cc1ff477207eb885d7ffbdcc2a36a8e90c06c4fd488bc9d932778abc9ec1e634ae1ddb8a",
          "sha256": "6e87b8c61c0e91445334903b848f412ba23343af61ff30ff610a8e0049b515cd",
          "sha1": "6d8e7e82c660e7a14f22d49ade75cabf32f2d89f",
          "md5": "08f3cca0a91f2685923127b12b1a5627"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.16.0.jar",
          "url": "core-ksp-processor-0.16.0.jar",
          "size": 33243,
          "sha512": "58c274b911f1b2ed1bdaee94e2475b1a300c29cd0e1a19cb2346b969cc1ff477207eb885d7ffbdcc2a36a8e90c06c4fd488bc9d932778abc9ec1e634ae1ddb8a",
          "sha256": "6e87b8c61c0e91445334903b848f412ba23343af61ff30ff610a8e0049b515cd",
          "sha1": "6d8e7e82c660e7a14f22d49ade75cabf32f2d89f",
          "md5": "08f3cca0a91f2685923127b12b1a5627"
        }
      ]
    }
  ]
}
