{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-foundation/0.4.0/core-foundation-0.4.0.module",
    "group": "com.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "core-foundation-android-0.4.0.aar",
          "size": 29397,
          "sha512": "917a4268118a14525ad72cef29c48d9d2198d39ee6e82799b6b58192d487293db952163ec0282df3a6a988b72e8bb4c3904fa36b28e0a6e50f3f909a8d1aac9a",
          "sha256": "0a079dcd3eb81d648a4f89f17b4591e4a08b3dc474ba3a00a2a7470fa0a4de64",
          "sha1": "71f3d23ddd28ab9230482db4957da6ee0d6b6622",
          "md5": "83de940546ba5ebe8e7578c43619a93a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "core-foundation-android-0.4.0.aar",
          "size": 29397,
          "sha512": "917a4268118a14525ad72cef29c48d9d2198d39ee6e82799b6b58192d487293db952163ec0282df3a6a988b72e8bb4c3904fa36b28e0a6e50f3f909a8d1aac9a",
          "sha256": "0a079dcd3eb81d648a4f89f17b4591e4a08b3dc474ba3a00a2a7470fa0a4de64",
          "sha1": "71f3d23ddd28ab9230482db4957da6ee0d6b6622",
          "md5": "83de940546ba5ebe8e7578c43619a93a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "foundation-android-0.4.0-sources.jar",
          "url": "core-foundation-android-0.4.0-sources.jar",
          "size": 10688,
          "sha512": "7689c440acf2db7c31f90117bbd178a891175495d8bf30edd18e361a446db183958f5c5f4c4c84b0f26c5a79fbd37bfabd73c12f82960317d87b08c885e7f85d",
          "sha256": "1905400caa1dad68217c14c3313969d2d546c33caf349290653b613d990bc4dc",
          "sha1": "c64d8bc89e6f877a01703ad9b55fbbe66f26bbff",
          "md5": "05f85129c8ebd8d5c4030fdc6eba70e8"
        }
      ]
    }
  ]
}
