{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-database/0.23.0/core-database-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-database",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "database-iosArm64Main-0.23.0.klib",
          "url": "database-iosarm64-0.23.0.klib",
          "size": 5862,
          "sha512": "a4472c21ed52f6bd4c02f035142770ef1b8eddfa1df66f2afb9625e191dad949d064d7fd071024608cb306f5cd908d378f4277f8bf391895151f2eb9d9ae5530",
          "sha256": "6301e8bd5dc31c0f6afa3b15c57259bcf59e339c82f38f232cb9b711572ddf61",
          "sha1": "a0639ad4339110554ea8b89c82ef66c635e61068",
          "md5": "8f9c6c7d6f310bc78c77c33a5570f9cf"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "database-iosarm64-0.23.0-sources.jar",
          "url": "database-iosarm64-0.23.0-sources.jar",
          "size": 2104,
          "sha512": "4490c10c602579a4558dadd16286df60598548bfc3080e3219a526e37db130140a319a4dda017d6124ec7f22799ce71059571723fc8fb30790f94f1f874e9f7d",
          "sha256": "aba816c8af3c5cd99718856e62b068ba054b269470163cda1b650ff6528fa9b3",
          "sha1": "d73da313d43e8ad8ab616ebec2906b0312caf837",
          "md5": "fcf5ff75f6c30576b4acf9df13f1e998"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "database-iosarm64-0.23.0-metadata.jar",
          "url": "database-iosarm64-0.23.0-metadata.jar",
          "size": 261,
          "sha512": "40f31ac0b23f74420192a9e644be3f099417f5b1d6d2b382e0c8921014250dfa2b69db82498df0610b52433a12626fc370027aacff28c7cc1de192494f34ba69",
          "sha256": "72b8e7c55617d9b23e6511333ac9eaa5ffe51b6a5680285a86e2cede51d6e0a7",
          "sha1": "62d26d117c7c8c1a10916e2fad1af09973e6914f",
          "md5": "09a0f8c109e956d793c7b7d282db6a11"
        }
      ]
    }
  ]
}
