{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.23.0.jar",
          "url": "core-ksp-processor-0.23.0.jar",
          "size": 33273,
          "sha512": "76ee225ae4a85b7f28ab4c2194cacf4e615a20a3823e0255dc7a0f8a46120048f5b75fc13197a27ea82f409504f9d70e1279fd51d5bf0a4140900fab6394a32b",
          "sha256": "34e6112c0c9c85711a8d54f9c03a6da579071977119a3efd558db2786dc8afb3",
          "sha1": "8e14913be71be2ce692497b2a43038af84ff2715",
          "md5": "2aefed9eb4a5c97e61d09aed06bc3913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.23.0.jar",
          "url": "core-ksp-processor-0.23.0.jar",
          "size": 33273,
          "sha512": "76ee225ae4a85b7f28ab4c2194cacf4e615a20a3823e0255dc7a0f8a46120048f5b75fc13197a27ea82f409504f9d70e1279fd51d5bf0a4140900fab6394a32b",
          "sha256": "34e6112c0c9c85711a8d54f9c03a6da579071977119a3efd558db2786dc8afb3",
          "sha1": "8e14913be71be2ce692497b2a43038af84ff2715",
          "md5": "2aefed9eb4a5c97e61d09aed06bc3913"
        }
      ]
    }
  ]
}
