{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.23.0.jar",
          "url": "core-ksp-processor-0.23.0.jar",
          "size": 33303,
          "sha512": "0f77ae0b8afd8fd832cb68cc6b84364a25601e16c8afe494e4980e85acda4dd9519c9bd9665f80430b45c201d82044a54456de8e64b86dadbe47f65bdc70ad91",
          "sha256": "1cf5b8314b08d04936f5bb282d560553d3cd3be91a8908f7668d158a3e4fd452",
          "sha1": "cf64fd86e7dec063fb6f8a25ff08d025b9a58f2b",
          "md5": "8627d6dee49c43d12bb441149629be97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.23.0.jar",
          "url": "core-ksp-processor-0.23.0.jar",
          "size": 33303,
          "sha512": "0f77ae0b8afd8fd832cb68cc6b84364a25601e16c8afe494e4980e85acda4dd9519c9bd9665f80430b45c201d82044a54456de8e64b86dadbe47f65bdc70ad91",
          "sha256": "1cf5b8314b08d04936f5bb282d560553d3cd3be91a8908f7668d158a3e4fd452",
          "sha1": "cf64fd86e7dec063fb6f8a25ff08d025b9a58f2b",
          "md5": "8627d6dee49c43d12bb441149629be97"
        }
      ]
    }
  ]
}
