{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger-posthog/0.23.0/core-logger-posthog-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger-posthog",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-posthog-release.aar",
          "url": "core-logger-posthog-android-0.23.0.aar",
          "size": 8353,
          "sha512": "1e55e1c7ae7553f0eefaaf11766158c61bbae0846cc88371540c34a78432f3ff568898a96ebd9247a28162a987aba3f9f674bd23f1ce942f69ddb12cc738eae1",
          "sha256": "e7b76ead5ea36aa089be79d23d17013d35d34176438014be6f6a2e053f06a846",
          "sha1": "10ebad76fc1afa5a8c7cade07f28fb31b8767d35",
          "md5": "f252a524a4cfd1ff8d37684dc065adda"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.23.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "logger-posthog-release.aar",
          "url": "core-logger-posthog-android-0.23.0.aar",
          "size": 8353,
          "sha512": "1e55e1c7ae7553f0eefaaf11766158c61bbae0846cc88371540c34a78432f3ff568898a96ebd9247a28162a987aba3f9f674bd23f1ce942f69ddb12cc738eae1",
          "sha256": "e7b76ead5ea36aa089be79d23d17013d35d34176438014be6f6a2e053f06a846",
          "sha1": "10ebad76fc1afa5a8c7cade07f28fb31b8767d35",
          "md5": "f252a524a4cfd1ff8d37684dc065adda"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logger-posthog-android-0.23.0-sources.jar",
          "url": "core-logger-posthog-android-0.23.0-sources.jar",
          "size": 4502,
          "sha512": "fd657030523ed31fe4e605724511b66c5f3e3633a9811a781b46441321460e0dd69e02095ca03be0d25e358f76c55ab14776a133cba9f0f88ba5e4813f3ae611",
          "sha256": "945b66d0a253a6e989b0d32cb68b5877a9524c6b20b6c630b450e63cb1ed37e9",
          "sha1": "f728eb000be2b49c039cd3253609af8b6270af5e",
          "md5": "0727e30881a9390c4082a1a9421087e0"
        }
      ]
    }
  ]
}
