{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig-posthog/0.27.0/core-remoteconfig-posthog-0.27.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-posthog",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-iosArm64Main-0.27.0.klib",
          "url": "core-remoteconfig-posthog-iosarm64-0.27.0.klib",
          "size": 16438,
          "sha512": "0111b06bb2de623939d2b94c5f53d37dd8a3a6d0b35672fb663a3e988ea0213661e5392a8348d629a20bc48b919145ef2864b3bb4a006e73a42472ec979c49b8",
          "sha256": "00035cfa6c6fa28a4b8c99f385c052bfbab1e2861e432a51171c1fa12dc6ba05",
          "sha1": "2412f1405f9b2dd86f2e6d7f60e4b7e22efe9273",
          "md5": "8df935b9247728e7122a8e1b69b34f4c"
        },
        {
          "name": "core-remoteconfig-posthog-iosArm64Cinterop-PostHogMain-0.27.0.klib",
          "url": "core-remoteconfig-posthog-iosarm64-0.27.0-cinterop-PostHog.klib",
          "size": 20942,
          "sha512": "b166aa1673ae2057e0e99d79dcb820323f377308df067a2e64d0282fdd82ae76281b5541ab2fa2fdd5f9cb34d2596da8acfb1349c32f0c4e30241a4167dc660d",
          "sha256": "b6183fa62a1c56015b62f553d237dc3250545434d729568a35e58a75013691f9",
          "sha1": "7d63581bec56ca69384126e0cef40a0426c0430a",
          "md5": "d64036304ab1509a8ceb2d6a4537f55c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-posthog-iosarm64-0.27.0-sources.jar",
          "url": "core-remoteconfig-posthog-iosarm64-0.27.0-sources.jar",
          "size": 5224,
          "sha512": "f011cc9ab80c3f5c23a15f78d071a90d573211ce6769fb2bcfb256a3f9f17d043ed5bf78bf3aa5eb1a2bcb62a0878cc238ff50b9aa0f3a39e1b3747d137746c0",
          "sha256": "509e63a4bceee9a217759e53e2f26326772dcdae702e701641f3c99dec7367f2",
          "sha1": "0869348d3acad764d6bae1b814141aa77a39921d",
          "md5": "00128daf39b5d3af1a3c976e6fc79a15"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-iosarm64-0.27.0-metadata.jar",
          "url": "core-remoteconfig-posthog-iosarm64-0.27.0-metadata.jar",
          "size": 56500,
          "sha512": "9874e258345117504cbc1b09867abcf248bb6a0c6170232f1bfd98ea95b9533665f7d19a756debface3ccab379d510b0eab200136ec79fd416eb7f54d7b922a6",
          "sha256": "a72ca07fb47380e19a695d2c7b51274df04ce203d36e318b704e5a8703636700",
          "sha1": "f8c808f2a2455faa3eddc362fc8103e33908c674",
          "md5": "f87b6356ded43813b94da4aa88d741d4"
        }
      ]
    }
  ]
}
