{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-0.10.0.jar",
          "url": "core-foundation-0.10.0.jar",
          "size": 10078,
          "sha512": "f65c6d495b9914e6346a0e7463a4a61a373e802f9bf9753fcd78abf2d61835f5a789caa601ad4bbb85e23888f0b3cd742dc923e5aeee5a7c1e1953d7540a095b",
          "sha256": "1e47eb4357572ff274bb9995a5345d7ead1840effe22ad62de63af7e706cc016",
          "sha1": "2fa4094e5f8869bfd541d3ca69e1edea37119a57",
          "md5": "3ef9787d77cc3685275eff3339bb1da1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "foundation-kotlin-0.10.0-sources.jar",
          "url": "core-foundation-0.10.0-sources.jar",
          "size": 9455,
          "sha512": "a1caf21557f63e6e258174b929b1944de2c4e64af7e641bbb18e7f286af5f2ea54b81cfa74cc8da99c566f7ef3dfb65c165f7f438a81fe4bbf5037b72ac99231",
          "sha256": "5c1e2d0abc50ca3bd0780197d238b41ce764a3ec315047621a52ff4bc5783ce0",
          "sha1": "9f3ffad7bb4cf0ac3c221431c603c400c4529cac",
          "md5": "19ff48f7028bcb4121cd08c618f1214a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.10.0/core-foundation-android-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.10.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.10.0/core-foundation-android-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.10.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.10.0/core-foundation-android-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.10.0/foundation-iosarm64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.10.0/foundation-iosarm64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.10.0/foundation-iosarm64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.10.0/foundation-iossimulatorarm64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.10.0/foundation-iossimulatorarm64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.10.0/foundation-iossimulatorarm64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.10.0/foundation-iosx64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.10.0/foundation-iosx64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.10.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.10.0/foundation-iosx64-0.10.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.10.0"
      }
    }
  ]
}
