{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.24.0.jar",
          "url": "core-ksp-processor-0.24.0.jar",
          "size": 33555,
          "sha512": "679067a89e95438b97c62e1119c5ce89ee8249ad7342826baffd35d6ce55c5bf2fab4a4e13a23be85e6413ddeea0da7486191c202278c9b51f5f1b944a19c0aa",
          "sha256": "d52da6ce64fd0367dee046ba64d8b872dc6830cbdd4682b07b6661d85bca17f2",
          "sha1": "42e9fb81a3a27fe6bbf7a9f378e2ea51886fb76d",
          "md5": "3fd1dd4144a815874954726afcc12564"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.24.0.jar",
          "url": "core-ksp-processor-0.24.0.jar",
          "size": 33555,
          "sha512": "679067a89e95438b97c62e1119c5ce89ee8249ad7342826baffd35d6ce55c5bf2fab4a4e13a23be85e6413ddeea0da7486191c202278c9b51f5f1b944a19c0aa",
          "sha256": "d52da6ce64fd0367dee046ba64d8b872dc6830cbdd4682b07b6661d85bca17f2",
          "sha1": "42e9fb81a3a27fe6bbf7a9f378e2ea51886fb76d",
          "md5": "3fd1dd4144a815874954726afcc12564"
        }
      ]
    }
  ]
}
