{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.27.0/core-remoteconfig-0.27.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-release.aar",
          "url": "core-remoteconfig-android-0.27.0.aar",
          "size": 22230,
          "sha512": "a3c12c327f595de5c0425f970bc68de40e9270f2a79b983109aad178ebfc748ec0e0e507a902615377a977365a93b47517780248525ae5cccc297086ef5a2854",
          "sha256": "82971a95a0121c2c8d50bf8c65ed124c88da09e073b593f6c5f71966de670cf6",
          "sha1": "cd65a4e9139741280b06bb52ee586f693e5abc4c",
          "md5": "ad6a1de93846651677d42ee518c06da6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-release.aar",
          "url": "core-remoteconfig-android-0.27.0.aar",
          "size": 22230,
          "sha512": "a3c12c327f595de5c0425f970bc68de40e9270f2a79b983109aad178ebfc748ec0e0e507a902615377a977365a93b47517780248525ae5cccc297086ef5a2854",
          "sha256": "82971a95a0121c2c8d50bf8c65ed124c88da09e073b593f6c5f71966de670cf6",
          "sha1": "cd65a4e9139741280b06bb52ee586f693e5abc4c",
          "md5": "ad6a1de93846651677d42ee518c06da6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-remoteconfig-android-0.27.0-sources.jar",
          "url": "core-remoteconfig-android-0.27.0-sources.jar",
          "size": 6158,
          "sha512": "5cc7a431be51a3ca4890d5426fa79db8156f7ca702e6a96729caf106048d29c88ac2a565fbb77e3ab12e30352d961a1e5919770ab027709254c03795a0999b8b",
          "sha256": "6b5d4855123e2c062240211f5ce45a94c1894066ffbcab6ce6297aa38da87796",
          "sha1": "323cea1e0eb45d376631b852c5d04be2c2b6eb43",
          "md5": "9f2b710637a33ddbd8445c996cb19ee3"
        }
      ]
    }
  ]
}
