{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger/0.23.0/core-logger-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-release.aar",
          "url": "core-logger-android-0.23.0.aar",
          "size": 55452,
          "sha512": "207689baf030c28b3c5b7acea9953fb7c0480fca04f1ce3a51e18b29e96936cbc171af90c78a23e283e663bb23085c5f350af3fad30c896889032a4140b0cb3f",
          "sha256": "def6d4288aaf420b24fe72b8ebc59fbe9adb77caaf08ac6d650dba8854c78f93",
          "sha1": "44de2ac3a3387e25bcde108a838837cf1fd87520",
          "md5": "05bceb7f888f106d8dee9ce8a38d9981"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "logger-release.aar",
          "url": "core-logger-android-0.23.0.aar",
          "size": 55452,
          "sha512": "207689baf030c28b3c5b7acea9953fb7c0480fca04f1ce3a51e18b29e96936cbc171af90c78a23e283e663bb23085c5f350af3fad30c896889032a4140b0cb3f",
          "sha256": "def6d4288aaf420b24fe72b8ebc59fbe9adb77caaf08ac6d650dba8854c78f93",
          "sha1": "44de2ac3a3387e25bcde108a838837cf1fd87520",
          "md5": "05bceb7f888f106d8dee9ce8a38d9981"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logger-android-0.23.0-sources.jar",
          "url": "core-logger-android-0.23.0-sources.jar",
          "size": 24131,
          "sha512": "204e122ebf42650f94793a4b95401176bc264dc91527b01f53522cd6280ec584630a243392cb155b6e5d2fb6dc1ee220aa6968e8595ff8808ef4ff402aaec087",
          "sha256": "2fc9601557282b6d02accf0f4079276cecf6495c0eddcaaf3c1733ec22e7575a",
          "sha1": "90d01d8cdbb3a1cad7f74d53fe95652264634248",
          "md5": "173e8a1eeb9a2437146b031c15a68ab0"
        }
      ]
    }
  ]
}
