{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-preferences/0.26.0/core-preferences-0.26.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-preferences",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-preferences-iosSimulatorArm64Main-0.26.0.klib",
          "url": "core-preferences-iossimulatorarm64-0.26.0.klib",
          "size": 5039,
          "sha512": "f88679c65f280131ea27afe0df93d3c432c287a105e7a54c4f01b7061119ef8fef035f23670f902151d25b47b681352e82efcd8bd0a4e9d5062814549c61a60f",
          "sha256": "75feb6128fb90dcefad852bd179e2c106a3114fc8afe8f7f9f265d27ff7cc19f",
          "sha1": "535d57ef21bec2944b792426878521f273ec9bc2",
          "md5": "5ebc441c40986ca2c6e957f12e9ac5c7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-preferences-iossimulatorarm64-0.26.0-sources.jar",
          "url": "core-preferences-iossimulatorarm64-0.26.0-sources.jar",
          "size": 3078,
          "sha512": "8dc16d8afea703bedb25cc3eb7152f853b67c88bb84aa8cfbdc826f635e224e6e652b4a58b6c4aaee20add23c4c01214eb28af2a67c00fe6499cee44bd37c217",
          "sha256": "9a379ceb90394249da7f24c9801a087b23d550193b18b9341e042b58840c36eb",
          "sha1": "7bb2dc4a022c988cdd03848805cb4ab79b9d56d7",
          "md5": "f7222ae5900ea344afadc100efc161e9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-preferences-iossimulatorarm64-0.26.0-metadata.jar",
          "url": "core-preferences-iossimulatorarm64-0.26.0-metadata.jar",
          "size": 2466,
          "sha512": "20445a865f5a70a29fa9b468dde0b56e232fe5cb035ec99ff3d137b94bcaff5a0fc1bb430fe053b3e2acc8ddaf9368f2f8fb04ffe93f95e30f0c64d97246a7a1",
          "sha256": "9b01484318ff85c04fe9c45074b8a00f3d98192a9110f3899cd3d20b566ae577",
          "sha1": "16ad90fd9408bb087a0f98d78229822cf31905aa",
          "md5": "a9b18c65a42eca8ea68d76974d1d3989"
        }
      ]
    }
  ]
}
