{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-foundation/0.23.0/core-foundation-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "core-foundation-android-0.23.0.aar",
          "size": 25314,
          "sha512": "18c02f35358b3889d4c68a1199e56c6331bc4b08285dfdb0cd9ef9e895992c51a328e6e4bace5dace0018cf8594b8a696c5303bd6a0e238db945ef37a2352149",
          "sha256": "25d5b96b4a0166a250ff16fc14ea57f6a5f14241274a8c33843fd5d7a6848cb2",
          "sha1": "315d98036e9b87b5e7fd492e7c74875204535352",
          "md5": "e71573a3e548ecbc782aef9982a33f20"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "core-foundation-android-0.23.0.aar",
          "size": 25314,
          "sha512": "18c02f35358b3889d4c68a1199e56c6331bc4b08285dfdb0cd9ef9e895992c51a328e6e4bace5dace0018cf8594b8a696c5303bd6a0e238db945ef37a2352149",
          "sha256": "25d5b96b4a0166a250ff16fc14ea57f6a5f14241274a8c33843fd5d7a6848cb2",
          "sha1": "315d98036e9b87b5e7fd492e7c74875204535352",
          "md5": "e71573a3e548ecbc782aef9982a33f20"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "foundation-android-0.23.0-sources.jar",
          "url": "core-foundation-android-0.23.0-sources.jar",
          "size": 9586,
          "sha512": "dda987a9f3e835f0ae5871a71a473c6e2ec4de91048102aebfd775d107f11234184fe7ed41fd1a19e2760d1237d78b95fb64729294d058f582fedc6bfff195b7",
          "sha256": "7be0675effcbb5dd631ec297918f376cd78664b7c61083c0567d6329c5d46e99",
          "sha1": "22f4340bb1e05eef7af7856cf88874fd54f75a71",
          "md5": "598a794ee1f3445d22dd80840f45bd07"
        }
      ]
    }
  ]
}
