{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-ui",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.8.0.aar",
          "url": "core-ui-0.8.0.aar",
          "size": 152676,
          "sha512": "286add7f0a4f369cb428f680a02c0ac032fb727aefbc5946d1f98d4b620eefdac6772223f67a8b55dba5af74f044172e5a7a0f2d51efd5b6004f8a525631c807",
          "sha256": "bfc71fe48ed76e0c9e356b007335f83b4c888ba4b3b5c7409efe3a9804b89ba5",
          "sha1": "6ab032307071200b688c1cf38d5ca82aa040329a",
          "md5": "763a4eba2f9e7e3a635eb6a3e3237822"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ui-0.8.0.aar",
          "url": "core-ui-0.8.0.aar",
          "size": 152676,
          "sha512": "286add7f0a4f369cb428f680a02c0ac032fb727aefbc5946d1f98d4b620eefdac6772223f67a8b55dba5af74f044172e5a7a0f2d51efd5b6004f8a525631c807",
          "sha256": "bfc71fe48ed76e0c9e356b007335f83b4c888ba4b3b5c7409efe3a9804b89ba5",
          "sha1": "6ab032307071200b688c1cf38d5ca82aa040329a",
          "md5": "763a4eba2f9e7e3a635eb6a3e3237822"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ui-0.8.0-sources.jar",
          "url": "core-ui-0.8.0-sources.jar",
          "size": 30985,
          "sha512": "062f4016513887a79881485252e1aaa9bba0a7a1afac7ef680254275094fc74a21372a8d36936d947020ad0eb892a6464a07c70b10a6b8650bb0ff3f0480403b",
          "sha256": "4cc3e52071fb25a330732fe561366f075dbc4067558a158840b02463a41bf32d",
          "sha1": "4bc5d3276877f0b2be677f88db6709923ac30b43",
          "md5": "ab40fd1eaf3ed9367c674e3ecc45a828"
        }
      ]
    }
  ]
}
