{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-di-koin",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.10.0.aar",
          "url": "core-di-koin-0.10.0.aar",
          "size": 18494,
          "sha512": "c56e93d54cf2a361c6e844ee3326b091111fa61d3c4d677f167c63e4cb124dc149126271cbaef0f819b399d435c94d931711b7729d4c12f406b810d3c5190dc9",
          "sha256": "491a114086561b94b097b250a928e43b812aad157152bff8fd0bc8cd5dd52ab8",
          "sha1": "04d3351cf2c6b18a993b1dfd773f61b727b079be",
          "md5": "8791788cb31cfee8570c5aa3f6f6cfba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-ui",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-di-koin-0.10.0.aar",
          "url": "core-di-koin-0.10.0.aar",
          "size": 18494,
          "sha512": "c56e93d54cf2a361c6e844ee3326b091111fa61d3c4d677f167c63e4cb124dc149126271cbaef0f819b399d435c94d931711b7729d4c12f406b810d3c5190dc9",
          "sha256": "491a114086561b94b097b250a928e43b812aad157152bff8fd0bc8cd5dd52ab8",
          "sha1": "04d3351cf2c6b18a993b1dfd773f61b727b079be",
          "md5": "8791788cb31cfee8570c5aa3f6f6cfba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-di-koin-0.10.0-sources.jar",
          "url": "core-di-koin-0.10.0-sources.jar",
          "size": 3619,
          "sha512": "b75368527786ffe12db6c0ef143dc8ce2afa0d58ed38fc9b53334804a6c333cd5d6664bfa79054adf5f8400e41aee944b3d4ea65529374ea11c67c7f0c551137",
          "sha256": "9ac6e2c20322461c3fd1c6248e83566eab7f310f9561f3e849db07942f7d1766",
          "sha1": "20dc08c96bb75fd94d616afe5952099d62d755a4",
          "md5": "587a691732b4161f44c5dae1d70dd03f"
        }
      ]
    }
  ]
}
