{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-0.2.0.jar",
          "url": "core-foundation-0.2.0.jar",
          "size": 8896,
          "sha512": "9cf43c5592d7f011bf2947a95c177449fadafb101ab325ab92fc99854048ddbeeae7f89531d64c8675ecf46c2c51633ebc11c6a1e5f7a23a796e49fa63d5eb39",
          "sha256": "baca5dcde7878602c859325051ad4320c02f95ad8d9b8bff4df972b1c2823bfb",
          "sha1": "0a1f5ffe121efeaa7e21bc4664b681408ab32a0d",
          "md5": "958af5e486085c7755a50e1b4c7ab14a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "foundation-kotlin-0.2.0-sources.jar",
          "url": "core-foundation-0.2.0-sources.jar",
          "size": 7814,
          "sha512": "16463121923de30fdcea69afcf3daf8c92e0b4aee41bd034b35f9d52871a0bbe0b81c97c1b738ce0851f56b1806fb262c446b6424f0004da462114c92860e59a",
          "sha256": "1a7bcb7bd6e85847836f56c8635a01e4d8b3a899f26e92c9692059208b645b9b",
          "sha1": "93448573be007bb047f1d5e1a291ef789918cff7",
          "md5": "3315dcc8fb991fccd6ddc8e76374a9a8"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.2.0/core-foundation-android-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.2.0/core-foundation-android-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-foundation-android/0.2.0/core-foundation-android-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "core-foundation-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.2.0/foundation-iosarm64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.2.0/foundation-iosarm64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosarm64/0.2.0/foundation-iosarm64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.2.0/foundation-iossimulatorarm64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.2.0/foundation-iossimulatorarm64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iossimulatorarm64/0.2.0/foundation-iossimulatorarm64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.2.0/foundation-iosx64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.2.0/foundation-iosx64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-iosx64/0.2.0/foundation-iosx64-0.2.0.module",
        "group": "com.dexkot.mobile",
        "module": "foundation-iosx64",
        "version": "0.2.0"
      }
    }
  ]
}
