{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-logger/0.23.0/core-logger-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-logger",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "logger-iosSimulatorArm64Main-0.23.0.klib",
          "url": "logger-iossimulatorarm64-0.23.0.klib",
          "size": 63187,
          "sha512": "cf81db878e5ae3a7d02610ee5f87e7f6d18c2ba5636ca21dcc73e8e0749e993d662ce6e4e906e0211d160387936a1511678fa60ffda76e3a1a2a9bcdb9fa0eea",
          "sha256": "b18318d3c3bbcb59c2e1c1ba9fae6a777e1d2340f7d0ef9b0909d1f669f5230d",
          "sha1": "ce4f823091323a5de44ddf5dfe01d0dfb8ad4b4a",
          "md5": "11cd753485186c03228583aabc9b2aa8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "logger-iossimulatorarm64-0.23.0-sources.jar",
          "url": "logger-iossimulatorarm64-0.23.0-sources.jar",
          "size": 23929,
          "sha512": "063dd56f60de910c07137f78ea6f157e3ee8477b7d76bc8b760ced901ad3a8361f9bc8966de424abcdb0d14012e5954171423a4f2f264f2042acee7b14b77869",
          "sha256": "6c8953055122a44d7eab85cdcd9d8f7c5c0d8809a05b3f45409624880819ea44",
          "sha1": "6bcf5e625931b3a117ba7ac205709a182b8013eb",
          "md5": "c457ec00f07b10a0da189f10e77a348b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "logger-iossimulatorarm64-0.23.0-metadata.jar",
          "url": "logger-iossimulatorarm64-0.23.0-metadata.jar",
          "size": 4211,
          "sha512": "f712eb45becff328c93622c7d4d94a876b3f1e10cbbbafac1e6af88eee5cdfa2e66d919abdf4bef4e2ebc0bd48c9f5aba0618df95738a3088c7630b20399533a",
          "sha256": "6c2cee6eb2b1f3ddd2ee18bdd26f255b03cc242b17eaf0d5ec25aa6b8eea5ade",
          "sha1": "a655a02dc2099dd868e6e37c93f1e3ec18926f6a",
          "md5": "84ed364462c1a80ac4c9602a855dd535"
        }
      ]
    }
  ]
}
