{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig-di-koin/0.26.0/core-remoteconfig-di-koin-0.26.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-di-koin",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-di-koin-iosArm64Main-0.26.0.klib",
          "url": "core-remoteconfig-di-koin-iosarm64-0.26.0.klib",
          "size": 6663,
          "sha512": "f5bdf0d30504937d6a603db153aeb6a3e69eb5753ea5eb3bbcbc7a554067fce529af697c20d3b311ef23463905c4162cbd0263d1b234eb43c6510cc09a2d5352",
          "sha256": "8692218b07be155bc21d8890b34df0ebf9c3475eb6048691b393fad7791eac9f",
          "sha1": "d8badb0c24f8c69377372115e2553b91ddc3674d",
          "md5": "dda5cae15e6452c58a75f0817da5d0b5"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-di-koin-iosarm64-0.26.0-sources.jar",
          "url": "core-remoteconfig-di-koin-iosarm64-0.26.0-sources.jar",
          "size": 2564,
          "sha512": "1e9ee83e376055496dc0723d343c80e299b8b14e164121c04d348711b42a766f88064a15f08c0794bcb91c7fb8e0f18e1d83b0c62d078d60869ebdd3c26e7071",
          "sha256": "2c7985abe2b01d903a3bd1464faa08fac264b48f8303cc89ba77a99a6bb87b19",
          "sha1": "82f93a0a184c968826abbec900f8488f9cf6bd42",
          "md5": "6067a3ad343bc40975d5eff10fd5be7a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-firebase",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig-posthog",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-di-koin-iosarm64-0.26.0-metadata.jar",
          "url": "core-remoteconfig-di-koin-iosarm64-0.26.0-metadata.jar",
          "size": 261,
          "sha512": "e9258fccfb5010ba79a98d69d334fbbdc665b8bc52c6e7120dcf1048db31e378610925a11bcc6aa3435875380165333a627a7373643b2e11ac6ffb71e0283daf",
          "sha256": "b2189bc5cb0ad1b9869bc04cc3e06c9273d2d6753035f2b0b209d5d92c83e0d7",
          "sha1": "0103a77fe0852ea49270dafbf96db017f1fd9813",
          "md5": "a3a7b80f074f0cc5159eba3970e91f53"
        }
      ]
    }
  ]
}
