{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.2.0.jar",
          "url": "core-ksp-processor-0.2.0.jar",
          "size": 33242,
          "sha512": "145e2d5212de1051ed50f1fc3754c8bdf7a29d39345226e4065903223c9e8b35dff1c7774301b8ecfda53ff2c91c92c80436ef1fc0b363b602e8b6ef2dc042dd",
          "sha256": "e26a6e850568ea52eff39aeed359bef2d860775361cd8057f7cf9ea594487688",
          "sha1": "9100c62b8ec4e894fab3875174328be32ecc37d8",
          "md5": "c7f8595ab79912ef85ea8c6d56287c88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.2.0.jar",
          "url": "core-ksp-processor-0.2.0.jar",
          "size": 33242,
          "sha512": "145e2d5212de1051ed50f1fc3754c8bdf7a29d39345226e4065903223c9e8b35dff1c7774301b8ecfda53ff2c91c92c80436ef1fc0b363b602e8b6ef2dc042dd",
          "sha256": "e26a6e850568ea52eff39aeed359bef2d860775361cd8057f7cf9ea594487688",
          "sha1": "9100c62b8ec4e894fab3875174328be32ecc37d8",
          "md5": "c7f8595ab79912ef85ea8c6d56287c88"
        }
      ]
    }
  ]
}
