{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-ksp-processor",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.7.0.jar",
          "url": "core-ksp-processor-0.7.0.jar",
          "size": 33242,
          "sha512": "b87a529277e7d0748b6e82fc6889727e9487a2036a73721e513b042026801ab32d4fc4a3b38e62f44b347e146fbc1424895eba4cd226c2b05816992f282d1416",
          "sha256": "1a47457eaa95b81816e56cdc9852f6faca061716745898ea0730c0065463960e",
          "sha1": "d66c08e2538741a54055b87577f0d4de7df0729e",
          "md5": "39abb1c2bd39dcae942f4ffc1e914d1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ksp-processor-0.7.0.jar",
          "url": "core-ksp-processor-0.7.0.jar",
          "size": 33242,
          "sha512": "b87a529277e7d0748b6e82fc6889727e9487a2036a73721e513b042026801ab32d4fc4a3b38e62f44b347e146fbc1424895eba4cd226c2b05816992f282d1416",
          "sha256": "1a47457eaa95b81816e56cdc9852f6faca061716745898ea0730c0065463960e",
          "sha1": "d66c08e2538741a54055b87577f0d4de7df0729e",
          "md5": "39abb1c2bd39dcae942f4ffc1e914d1b"
        }
      ]
    }
  ]
}
