{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-foundation/0.24.1/core-foundation-0.24.1.module",
    "group": "dev.dexkot.mobile",
    "module": "core-foundation",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-foundation-iosArm64Main-0.24.1.klib",
          "url": "core-foundation-iosarm64-0.24.1.klib",
          "size": 24203,
          "sha512": "edceed1b45f7895adc81b5fc544e342b64ca1d6209b7afb9fc4b350950833c335995f13963ceb5347e751408dc293986329b0f4f7847481744142f9fc7bc7bdc",
          "sha256": "46a190d189b1000beef7f551e72fc7cdfd25d6b1d93b7d9bfc0516a24a57c71b",
          "sha1": "467aebaa546235c32fa428315364a45e2f31a59f",
          "md5": "4eb4e10e570061bc5135fa077af81552"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-foundation-iosarm64-0.24.1-sources.jar",
          "url": "core-foundation-iosarm64-0.24.1-sources.jar",
          "size": 10044,
          "sha512": "301e52da4947b1ca0416e5404ae7830ad722f986fc6b37c4757df7eb83afc2e9584b6a80c750f05f892fbf536fc88c741e138aa8db5cc024c241a3efed1b7e61",
          "sha256": "56e7181e02e3fd9276205dc170af2417ff870ab96c3b8a74eeaa751f3d5ee29a",
          "sha1": "15c9a445b8eef4309cf445a3f83373e7012f6a42",
          "md5": "35f8ed77d8a277b84a2e0e756d85853c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-foundation-iosarm64-0.24.1-metadata.jar",
          "url": "core-foundation-iosarm64-0.24.1-metadata.jar",
          "size": 3504,
          "sha512": "e643507d1cbe92d73a21716170e5998fe9672f1eb0d09b3ed8c6e3582edfa2da2e51ce8eb790cbe7686dffb4a952d3ce93fcabdbd526b31c16e172d732f11c59",
          "sha256": "6cb5ac49180ac4e5bf58d4ae9cf1f529d194359a31d4ebf2fb15475b3f4a6239",
          "sha1": "111dde1c1220fe3f94b54cbfeffb05fff1c67020",
          "md5": "1fdab743afeb42a61878e140887f72f8"
        }
      ]
    }
  ]
}
