{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-logger-di-koin",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-firebase",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger-posthog",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-di-koin-metadata-0.25.0.jar",
          "url": "core-logger-di-koin-0.25.0.jar",
          "size": 2512,
          "sha512": "d1ca0f847b8a4607b03a805aa5cc21571a703dea51530bbdab46c4367ce862d10e81239bd02d8175d13d7cfc173ece09e0b29c07abc833d322f80e1a3bfaeacf",
          "sha256": "463d20b2ea23befdfee16d9d667f573998e2900aa8a9dec9618eef597e5ea864",
          "sha1": "b4dea271440779bf20df1929e056a56ce70801b6",
          "md5": "3f2dc48e7b44d11571da7ec6154b80ce"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-logger-di-koin-kotlin-0.25.0-sources.jar",
          "url": "core-logger-di-koin-0.25.0-sources.jar",
          "size": 2287,
          "sha512": "1338703693fb1a6c4301e021619ed48199d94a4114428fab4470d01bfea4351ae46036142ce404e721b70a99afc9d4d2db6ed44d9edd3e736d3740f09d3c7bae",
          "sha256": "fcd782b1048fd9f658e704c1fbb5c411307a91e3f8c70cb6acbc0e1bac4dc976",
          "sha1": "13a4625d6400e608d13eac58cfd4f69664a8ef3e",
          "md5": "91c59ea784d016b7d08c04368268833c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-android/0.25.0/core-logger-di-koin-android-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-android/0.25.0/core-logger-di-koin-android-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-android/0.25.0/core-logger-di-koin-android-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-iosarm64/0.25.0/core-logger-di-koin-iosarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-iosarm64/0.25.0/core-logger-di-koin-iosarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-iosarm64/0.25.0/core-logger-di-koin-iosarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-iossimulatorarm64/0.25.0/core-logger-di-koin-iossimulatorarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-iossimulatorarm64/0.25.0/core-logger-di-koin-iossimulatorarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-logger-di-koin-iossimulatorarm64/0.25.0/core-logger-di-koin-iossimulatorarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-logger-di-koin-iossimulatorarm64",
        "version": "0.25.0"
      }
    }
  ]
}
