{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-remoteconfig-posthog",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-0.9.0.aar",
          "url": "core-remoteconfig-posthog-0.9.0.aar",
          "size": 13212,
          "sha512": "b00249b2766ebd8b39b8df10647955fc1eb685173c85f6eaad82481ca62cac1b1e5475f0f1e658d232d60b61f3b27a41f6cf6cf07720152f2797838ebdc11fff",
          "sha256": "9ec32cda26422be4b24cfccbceb525329a409d9ae847d09fb377e33ebe247036",
          "sha1": "5d16ca67486d1e7547101dee4ad2170d98cee89a",
          "md5": "d6416644d349662c32922117e68680ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.posthog",
          "module": "posthog-android",
          "version": {
            "requires": "3.47.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-posthog-0.9.0.aar",
          "url": "core-remoteconfig-posthog-0.9.0.aar",
          "size": 13212,
          "sha512": "b00249b2766ebd8b39b8df10647955fc1eb685173c85f6eaad82481ca62cac1b1e5475f0f1e658d232d60b61f3b27a41f6cf6cf07720152f2797838ebdc11fff",
          "sha256": "9ec32cda26422be4b24cfccbceb525329a409d9ae847d09fb377e33ebe247036",
          "sha1": "5d16ca67486d1e7547101dee4ad2170d98cee89a",
          "md5": "d6416644d349662c32922117e68680ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-remoteconfig-posthog-0.9.0-sources.jar",
          "url": "core-remoteconfig-posthog-0.9.0-sources.jar",
          "size": 2617,
          "sha512": "ae32ffdf46a994f718d44d9dccdd5f3130268414dbbfe8b06e7c7e0e0603f0022895cc0937a396c61149fcb88d518f58b4f352124caa4087ff20f1a3b0b60bcc",
          "sha256": "7a39cffda1e1ad11f12b7b0fae487467ccd8a41afd556b2fc19914c2887f373f",
          "sha1": "112c1de29e3a4fa960288c0405e0345c93ee2a8b",
          "md5": "109782117e3658aec53199ab3770153d"
        }
      ]
    }
  ]
}
