{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-work/0.24.2/core-work-0.24.2.module",
    "group": "dev.dexkot.mobile",
    "module": "core-work",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-iosArm64Main-0.24.2.klib",
          "url": "core-work-iosarm64-0.24.2.klib",
          "size": 40039,
          "sha512": "aa843152c709a7bc307dd10274d83447d233f1f13c035508f26762677bea7d9c09aed14309a01f6ec5347949cb89c52689c8a4caf9b567eef38d2a66e458f07c",
          "sha256": "106f02c363539bd751f835169b4a68e8673bb6908362393a296db71681bdb716",
          "sha1": "e79be46bbf9eebcacab49757bbc6ee6d9a237bd1",
          "md5": "f93872da6c3cf9cc30ee2769a8f0f193"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-work-iosarm64-0.24.2-sources.jar",
          "url": "core-work-iosarm64-0.24.2-sources.jar",
          "size": 18515,
          "sha512": "68404b19ed1187697bd59dc943ad2e05226772004bad36ad4933fd8555b5576e1ae6596a1ade42366006de50e0f6b3a0c7f4a6440249fd8bd6f65a532ab8d352",
          "sha256": "14bb823510823f1fa170c49fe2876b94b636f26eb295a88a14fe3bc029d2d74b",
          "sha1": "a0906f3d1d58da4b786d774e26a0b952b220d6bb",
          "md5": "1c3dae832cc7d6b7d068ae414f662182"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-iosarm64-0.24.2-metadata.jar",
          "url": "core-work-iosarm64-0.24.2-metadata.jar",
          "size": 261,
          "sha512": "0d15262e648e9802150fbf03e107b40814c4c63e82b864034c2899e429b564da924cb337c903b8a61165608078f3a5a43c3fd295594c2b614b82918c1e2d870f",
          "sha256": "feaed53780a03c43d1569885c247ae58dda833de3a3f099733794b374688ff1a",
          "sha1": "bc2e6fab6e6108dd63d0301625fc9be04d895d08",
          "md5": "fbe86a411623ebe34eca976940e9d67c"
        }
      ]
    }
  ]
}
