{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-0.9.0.aar",
          "url": "core-remoteconfig-0.9.0.aar",
          "size": 25619,
          "sha512": "45acae5b6c4d5fe009890331e4abddb8b0d082c311033c3ea5dceb99ebb2caecfb45799f1524e36f719f7d99d01d92104e122da578f83702bb1e7cf6d78b4519",
          "sha256": "d26186ce441fe651bb003c9b0675f312655548563071dc3e2e8809a4e1ff1afe",
          "sha1": "596a0bf061d441e5266a1313b3b022a76d498d16",
          "md5": "5c2c7697cdc38c9d3fbbb2dfbb26f291"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-0.9.0.aar",
          "url": "core-remoteconfig-0.9.0.aar",
          "size": 25619,
          "sha512": "45acae5b6c4d5fe009890331e4abddb8b0d082c311033c3ea5dceb99ebb2caecfb45799f1524e36f719f7d99d01d92104e122da578f83702bb1e7cf6d78b4519",
          "sha256": "d26186ce441fe651bb003c9b0675f312655548563071dc3e2e8809a4e1ff1afe",
          "sha1": "596a0bf061d441e5266a1313b3b022a76d498d16",
          "md5": "5c2c7697cdc38c9d3fbbb2dfbb26f291"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-remoteconfig-0.9.0-sources.jar",
          "url": "core-remoteconfig-0.9.0-sources.jar",
          "size": 4524,
          "sha512": "b71505b129a5a31636ce64c3a6c07e774a530dfdb577749808798e1f8eba424a4a272e6798df2b278710103e8c7c1c756df539d0cad4881a488a65da20979877",
          "sha256": "309ffc5455207f3b06c1981a6b9188ca3a09ddb3c58a7a891dff1c11126a033b",
          "sha1": "9b1c8eee0451c9f99a75f991ddabc3282d302fc9",
          "md5": "a8fde4f506aada77fb8bc9f142b76b84"
        }
      ]
    }
  ]
}
