{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-work",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-work-metadata-0.25.0.jar",
          "url": "core-work-0.25.0.jar",
          "size": 22165,
          "sha512": "cca9e30439b7ebac54ed61d25e2046cc62d541d653df917af16b6187bcbcf9b73575f9463e65da51a6e1570151c50bb5438b3c7b3669a5e2f2f8f1958179cbb9",
          "sha256": "5b8fe92a20113d31733356473b1d046347e4bee76cd18387c90053f25aa32d21",
          "sha1": "fb20ed284590a6a8d16e8b01ac07c18b1aef8249",
          "md5": "b128fbc0f0d628c3bfbfa663aaa4bfd1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-work-kotlin-0.25.0-sources.jar",
          "url": "core-work-0.25.0-sources.jar",
          "size": 25976,
          "sha512": "22c5fb54113421684ed0150038bcd931caeb4294bac796ca118c88ade9b53e84b33a5ae89666c9018177fb843eb8052875ba74a7fbfe1333a0ad0e065dd5f3b4",
          "sha256": "ae5842426c1bc8607192f16aaec09e5220a818af5a74f871a851fbeaac9bd53c",
          "sha1": "6b5608739049538d939614a8333b168bd12fb839",
          "md5": "4f819f6ccaebab92c04cab94960f28e0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.25.0/core-work-android-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.25.0/core-work-android-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.25.0/core-work-android-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-work-iosarm64/0.25.0/core-work-iosarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-work-iosarm64/0.25.0/core-work-iosarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-work-iosarm64/0.25.0/core-work-iosarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-work-iossimulatorarm64/0.25.0/core-work-iossimulatorarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-work-iossimulatorarm64/0.25.0/core-work-iossimulatorarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-work-iossimulatorarm64/0.25.0/core-work-iossimulatorarm64-0.25.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-iossimulatorarm64",
        "version": "0.25.0"
      }
    }
  ]
}
