{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-preferences/0.25.0/core-preferences-0.25.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-preferences",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-preferences-iosArm64Main-0.25.0.klib",
          "url": "core-preferences-iosarm64-0.25.0.klib",
          "size": 4973,
          "sha512": "8f65c05470bb89ea6b278406285bae72e90586643f9655153695047c9ab540c9cf57607ef6948454e6d5508bfbd0d8e1d18517dcb192915f79d275733be7314d",
          "sha256": "ce77545ceee2c8ac4e09eae190b9c7263ca085ea54385d981691863c2d7f4dad",
          "sha1": "f4e5fb602ace62aab72d52dd4a3e73b0edba7838",
          "md5": "fd35f3270627b38eacff17678b6988e0"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-preferences-iosarm64-0.25.0-sources.jar",
          "url": "core-preferences-iosarm64-0.25.0-sources.jar",
          "size": 3078,
          "sha512": "8dc16d8afea703bedb25cc3eb7152f853b67c88bb84aa8cfbdc826f635e224e6e652b4a58b6c4aaee20add23c4c01214eb28af2a67c00fe6499cee44bd37c217",
          "sha256": "9a379ceb90394249da7f24c9801a087b23d550193b18b9341e042b58840c36eb",
          "sha1": "7bb2dc4a022c988cdd03848805cb4ab79b9d56d7",
          "md5": "f7222ae5900ea344afadc100efc161e9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-preferences-iosarm64-0.25.0-metadata.jar",
          "url": "core-preferences-iosarm64-0.25.0-metadata.jar",
          "size": 2466,
          "sha512": "e7158713684ae49b8ac20dd7208af683efd124f300f3e010f3385c9b641898fee8b27d0e79f4f3d93735cf1698ca81bc78920fae715ba4e8cf867d3333acb324",
          "sha256": "7b5313d2ee8b3030799da26eef2ea15878480cf0d0167a6a917534bed6b4fccb",
          "sha1": "4b1de999331e92e35c589fc44b5c6461399010a1",
          "md5": "718cf1b34d7ad0fe8ec7267e45dcdaf5"
        }
      ]
    }
  ]
}
