{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig-firebase",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-remoteconfig",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "remoteconfig-firebase-metadata-0.23.0.jar",
          "url": "core-remoteconfig-firebase-0.23.0.jar",
          "size": 3874,
          "sha512": "456468ecc249054ac73bd8e383c97bc5c750ac29046f3d27284fc24c1b184d87c9ba63b5fa5e2a09885904fb336ceab050c2c73e3a32ba0a198c8cd5db565e5f",
          "sha256": "e007dcddbfe1cd2c8578da84864ed4f8e6b692b65831f1d0f30cb34164185e34",
          "sha1": "05c6351d969c357de54ff35436d5c2cee86824d0",
          "md5": "3bd84ab0e3bb7b67574052e78cf76f4f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "remoteconfig-firebase-kotlin-0.23.0-sources.jar",
          "url": "core-remoteconfig-firebase-0.23.0-sources.jar",
          "size": 5635,
          "sha512": "5db7df3f0eb5cc666de8156017a824bf2c270720f6af761ddbe69c76b9f5a4dcf537827af6015c06404d62e0c66b97abed161dc9761153a1bdd7252fd4fbac12",
          "sha256": "26f5e4ff9ac369446c2e265ae55c6492422f6af2edb41a73381d7ecc52774cb7",
          "sha1": "3efc4a067c288408af0634eb1fa565f626c96120",
          "md5": "a7c788a174baf7a2bfe26fa29fb225b1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-remoteconfig-firebase-android/0.23.0/core-remoteconfig-firebase-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-remoteconfig-firebase-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-remoteconfig-firebase-android/0.23.0/core-remoteconfig-firebase-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-remoteconfig-firebase-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-remoteconfig-firebase-android/0.23.0/core-remoteconfig-firebase-android-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-remoteconfig-firebase-android",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iosarm64/0.23.0/remoteconfig-firebase-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iosarm64/0.23.0/remoteconfig-firebase-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iosarm64/0.23.0/remoteconfig-firebase-iosarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iosarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iossimulatorarm64/0.23.0/remoteconfig-firebase-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iossimulatorarm64/0.23.0/remoteconfig-firebase-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iossimulatorarm64/0.23.0/remoteconfig-firebase-iossimulatorarm64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iossimulatorarm64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iosx64/0.23.0/remoteconfig-firebase-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iosx64/0.23.0/remoteconfig-firebase-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iosx64",
        "version": "0.23.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../remoteconfig-firebase-iosx64/0.23.0/remoteconfig-firebase-iosx64-0.23.0.module",
        "group": "dev.dexkot.mobile",
        "module": "remoteconfig-firebase-iosx64",
        "version": "0.23.0"
      }
    }
  ]
}
