{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-remoteconfig/0.24.2/core-remoteconfig-0.24.2.module",
    "group": "dev.dexkot.mobile",
    "module": "core-remoteconfig",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosArm64Main-0.24.2.klib",
          "url": "core-remoteconfig-iosarm64-0.24.2.klib",
          "size": 16948,
          "sha512": "faee1fb5e1f2584b825aa13af20801db200e6ff9b01999bb3a7a06d64a20971eb194a2c7d5ba40f69bb2931b66b9710d48c251fff7ad845ae042fb9448e365c2",
          "sha256": "76ee0fe7796ddbdd6ef73ad4f0c5ea9144897756e7fb26459cc53eee14f21ce5",
          "sha1": "dcee656203d4e15a78a723068a13ae578c6b7bd2",
          "md5": "bd2099e78042b6e7ea835d93932e5414"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.24.2-sources.jar",
          "url": "core-remoteconfig-iosarm64-0.24.2-sources.jar",
          "size": 5911,
          "sha512": "80324a440ee63060b4ec2b7238516b6e191d40d41e5719093e2731b9b124ca1c0500be21264301227c132f7c840e291b6bcfcbe990e20d0230fb37fd91cec712",
          "sha256": "31c6b3dd523d0dfa8013d82c7080448dcb4621ebcbf25394f00ab957cf18863e",
          "sha1": "58b7aaf98ebce30a132bd2e82f05902727e98b86",
          "md5": "73fa0791cfbd433abc542059e2a5593b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "dev.dexkot.mobile",
          "module": "core-logger",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteconfig-iosarm64-0.24.2-metadata.jar",
          "url": "core-remoteconfig-iosarm64-0.24.2-metadata.jar",
          "size": 261,
          "sha512": "36ff79c9a117f3bb67975f8a5aeb7ae58d5b618e1a7549568bc52b3b229bad66b2181ba0fc6f47a899309f487bf00f31f9c7d2745a60f85207d31119d6dcb27a",
          "sha256": "429d611035fc1b558589d8fb22770d8f39bcbc5213c8a091c8c60be95a540cbd",
          "sha1": "24b6bf20b240936c6da6a9702d5778da35a4fa52",
          "md5": "85d207e461cc5ce90429de5ca3e23347"
        }
      ]
    }
  ]
}
