{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.dexkot.mobile",
    "module": "core-work",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "work-metadata-0.20.0.jar",
          "url": "core-work-0.20.0.jar",
          "size": 16623,
          "sha512": "240054cc41e0e193248137984cd81449ecd5288461457477a4230a8021c6846af4ae7b7e4d43bcb325670f413f7194362ea25091b02d5b258a58e5cf3f72a15a",
          "sha256": "69483d7b70f21ee37b991e6e8543b877759dbe97950b210f32f43aa27fb26f9e",
          "sha1": "9b69a9f8d8a81e6f1570d9ac7164f90548aa1167",
          "md5": "419c1cf2421a78af32d61cdbff7a20e5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "work-kotlin-0.20.0-sources.jar",
          "url": "core-work-0.20.0-sources.jar",
          "size": 18377,
          "sha512": "81a112f5e67033c30c69f5c4ebf8bea8dfb5eebec6fc987482f4ea4e7bbf004991706e5fe91e80c0c7d836713273018b7b3b0c9f808fce82fcebd25220820d6e",
          "sha256": "4c1af2457529401a1f4d65711ab505da3d389ca3e996d322aa5297594680aa40",
          "sha1": "9984ade87e509c417f82d6e457ccf36109325da2",
          "md5": "e6cb5249a77e73d6710c754c491b5aaa"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.20.0/core-work-android-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.20.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.20.0/core-work-android-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.20.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-work-android/0.20.0/core-work-android-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "core-work-android",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosarm64/0.20.0/work-iosarm64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosarm64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosarm64/0.20.0/work-iosarm64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosarm64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosarm64/0.20.0/work-iosarm64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosarm64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iossimulatorarm64/0.20.0/work-iossimulatorarm64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iossimulatorarm64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iossimulatorarm64/0.20.0/work-iossimulatorarm64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iossimulatorarm64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iossimulatorarm64/0.20.0/work-iossimulatorarm64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iossimulatorarm64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosx64/0.20.0/work-iosx64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosx64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosx64/0.20.0/work-iosx64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosx64",
        "version": "0.20.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../work-iosx64/0.20.0/work-iosx64-0.20.0.module",
        "group": "dev.dexkot.mobile",
        "module": "work-iosx64",
        "version": "0.20.0"
      }
    }
  ]
}
