{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-database/0.23.0/core-database-0.23.0.module",
    "group": "dev.dexkot.mobile",
    "module": "core-database",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "database-release.aar",
          "url": "core-database-android-0.23.0.aar",
          "size": 5333,
          "sha512": "f7818370f652e43782b96a5cc4b4f533ad51092b67f6fac574d5560e2a78c8c00e79d35fa31c282296766dd92dd266812bed88d5087d1178bef72e42b9e2f7a7",
          "sha256": "493a55c00c9706de189af92640c0eccc80a4d512496c09085a9d854f3319d0b8",
          "sha1": "7d824894d59384b7a0665ae270782fa6b893145a",
          "md5": "1f05841b1a2116c4ec3fdcaf66a6786c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.dexkot.mobile",
          "module": "core-foundation",
          "version": {
            "requires": "0.23.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-release.aar",
          "url": "core-database-android-0.23.0.aar",
          "size": 5333,
          "sha512": "f7818370f652e43782b96a5cc4b4f533ad51092b67f6fac574d5560e2a78c8c00e79d35fa31c282296766dd92dd266812bed88d5087d1178bef72e42b9e2f7a7",
          "sha256": "493a55c00c9706de189af92640c0eccc80a4d512496c09085a9d854f3319d0b8",
          "sha1": "7d824894d59384b7a0665ae270782fa6b893145a",
          "md5": "1f05841b1a2116c4ec3fdcaf66a6786c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "database-android-0.23.0-sources.jar",
          "url": "core-database-android-0.23.0-sources.jar",
          "size": 2104,
          "sha512": "4490c10c602579a4558dadd16286df60598548bfc3080e3219a526e37db130140a319a4dda017d6124ec7f22799ce71059571723fc8fb30790f94f1f874e9f7d",
          "sha256": "aba816c8af3c5cd99718856e62b068ba054b269470163cda1b650ff6528fa9b3",
          "sha1": "d73da313d43e8ad8ab616ebec2906b0312caf837",
          "md5": "fcf5ff75f6c30576b4acf9df13f1e998"
        }
      ]
    }
  ]
}
