{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexkot.mobile",
    "module": "core-annotation",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-annotation-0.10.0.aar",
          "url": "core-annotation-0.10.0.aar",
          "size": 4023,
          "sha512": "8dd087c0f17ed7bdc4bf4b838a54a39cffe8fdec535fcee51daf92c8fef359f94e0a69e37674dc359cab5bfb7b10891eb316ddb71c58b4dce6dbe9cc19f3abc5",
          "sha256": "4e0d31dd42c12708f91c38300780ec342681872ce6137281d2e0f6ead78fc0a3",
          "sha1": "a61c68972a85f509928c4c18589f7f24c7e41369",
          "md5": "8cefc2dcd774ef919bc9bfd6d6f2da4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-annotation-0.10.0.aar",
          "url": "core-annotation-0.10.0.aar",
          "size": 4023,
          "sha512": "8dd087c0f17ed7bdc4bf4b838a54a39cffe8fdec535fcee51daf92c8fef359f94e0a69e37674dc359cab5bfb7b10891eb316ddb71c58b4dce6dbe9cc19f3abc5",
          "sha256": "4e0d31dd42c12708f91c38300780ec342681872ce6137281d2e0f6ead78fc0a3",
          "sha1": "a61c68972a85f509928c4c18589f7f24c7e41369",
          "md5": "8cefc2dcd774ef919bc9bfd6d6f2da4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-annotation-0.10.0-sources.jar",
          "url": "core-annotation-0.10.0-sources.jar",
          "size": 3101,
          "sha512": "deb4ee83219f56a70c358f045b5a822a94949c62c0836abfe6e46009bcd45e0b346d69d70d8a125f0fa3fa42b8ea5b1aa1df8ceaebdfcb935a2667be9b267a95",
          "sha256": "4d8639261469d0c312143d1c06fda0185c6999d2ae8b9780610d40c620523b91",
          "sha1": "3c265cb3679705c711e70f3de4f7738a80f39fe2",
          "md5": "c4308f11a35ad8c883cce7e093d946f2"
        }
      ]
    }
  ]
}
